import { test, expect } from '../../test-support/setupAuth'
import { syncLV } from '../../utils'
import { e2eUrl } from '../../test-support/e2eUrl'

test.skip(process.env.BRANDO_AUTHORIZATION_MODE !== 'groups', 'Requires explicit group mode')

test('manages a custom group with a reviewed permission change and membership', async ({ page }) => {
  await page.goto('/admin')
  await syncLV(page)
  await page.locator('#navigation [data-nav-expand]').filter({ hasText: 'Configuration' }).click()
  await page.getByRole('link', { name: 'Permissions', exact: true }).click()
  await syncLV(page)
  await expect(page.getByRole('heading', { name: 'Permissions', level: 1, exact: true })).toBeVisible()
  await expect(page.locator('#navigation dd a[href="/admin/groups"]')).toHaveText('Permissions')
  await expect(page.locator('#navigation dt a[href="/admin/groups"]')).toHaveCount(0)
  await page.getByRole('button', { name: 'New group' }).click()
  await expect(page.getByLabel('Group name', { exact: true })).toHaveValue('')
  await page.getByLabel('Group name', { exact: true }).fill('Campaign editors')
  await page.getByLabel('Description', { exact: true }).fill('The team behind our seasonal stories.')
  await page.locator('input[name="permissions[brando.admin.access]"]').check()
  await page.locator('input[name="permissions[brando.pages.read]"]').check()
  await page.locator('input[name="permissions[brando.pages.update]"]').check()
  await page.getByRole('button', { name: 'Review changes', exact: true }).click()
  await expect(page.locator('#authorization-review-title')).toBeFocused()
  await page.screenshot({ path: '/private/tmp/authorization-review-desktop.png', fullPage: true })
  await expect(page.locator('.authorization-review')).toContainText('3 permissions added')
  await page.getByRole('button', { name: 'Confirm & save' }).click()
  await expect(page.getByRole('status')).toContainText('Group saved')

  await page.getByRole('button', { name: /^Members/ }).click()
  await page.getByRole('button', { name: 'Add member', exact: true }).click()
  await page.getByRole('button', { name: 'Add Brando Admin', exact: true }).click()
  await expect(page.locator('.authorization-person')).toContainText('Brando Admin')
  await page.getByRole('button', { name: 'View access', exact: true }).click()
  await expect(page.locator('.authorization-effective')).toContainText('Protected Superuser access')
  await page.getByRole('button', { name: 'Activity', exact: true }).click()
  await expect(page.locator('.authorization-activity')).toContainText('Membership added')

  await page.getByRole('button', { name: 'Permissions', exact: true }).click()
  await page.screenshot({ path: '/private/tmp/authorization-groups-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 768, height: 1024 })
  await expect(page.locator('.authorization-editor')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: '/private/tmp/authorization-groups-tablet.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByLabel('Pages: Edit', { exact: true }).uncheck()
  await page.getByRole('button', { name: 'Review changes', exact: true }).click()
  await expect(page.locator('#authorization-review-title')).toBeFocused()
  await expect(page.locator('.authorization-review')).toContainText('1 permission removed')
  await page.getByRole('button', { name: 'Back to editing' }).click()
  await syncLV(page)
  await expect(page.getByRole('button', { name: 'Review changes', exact: true })).toBeFocused()
  await expect(page.getByLabel('Pages: View', { exact: true })).toBeVisible()
  await page.screenshot({ path: '/private/tmp/authorization-groups-mobile.png', fullPage: true })
})

test('keeps filtered grants and unsaved changes through navigation and keyboard review', async ({ page }) => {
  await page.goto('/admin/groups')
  await syncLV(page)
  await page.getByRole('button', { name: 'New group', exact: true }).click()
  await expect(page.getByLabel('Group name', { exact: true })).toHaveValue('')
  await page.getByLabel('Group name', { exact: true }).fill('Filtered reviewers')
  await page.getByLabel('Backend: Access', { exact: true }).check()
  await page.getByLabel('Pages: View', { exact: true }).check()
  await page.getByLabel('Pages: Edit', { exact: true }).check()
  await page.getByLabel('Find a permission', { exact: true }).fill('Pages')
  await expect(page.getByLabel('Backend: Access', { exact: true })).toHaveCount(0)
  await page.getByLabel('Pages: Edit', { exact: true }).uncheck()
  const cancelled = page.waitForEvent('dialog').then(async dialog => {
    expect(dialog.message()).toContain('unsaved')
    await dialog.dismiss()
  })
  await page.getByRole('link', { name: 'Installation groups' }).click()
  await cancelled
  await expect(page).toHaveURL('/admin/groups')
  await expect(page.getByLabel('Group name', { exact: true })).toHaveValue('Filtered reviewers')
  await page.getByRole('button', { name: 'Review changes', exact: true }).focus()
  await page.keyboard.press('Enter')
  await expect(page.locator('#authorization-review-title')).toBeFocused()
  await expect(page.locator('.authorization-review')).toContainText('2 permissions added')
  await expect(page.locator('.authorization-review')).toContainText('Backend · Access')
  await expect(page.locator('.authorization-review')).not.toContainText('Pages · Edit')
  await page.getByRole('button', { name: 'Confirm & save' }).click()
  await expect(page.getByRole('status')).toContainText('Group saved')
  await expect(page.getByRole('button', { name: 'Review changes', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: /^Members/ }).click()
  await page.getByRole('button', { name: 'Permissions', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Review changes', exact: true })).toBeDisabled()
})

test('selects a permission row with mixed state, keyboard support and search boundaries', async ({ page }) => {
  await page.goto('/admin/groups')
  await syncLV(page)
  await page.getByRole('button', { name: 'New group', exact: true }).click()
  await expect(page.getByLabel('Group name', { exact: true })).toHaveValue('')
  await page.getByLabel('Group name', { exact: true }).fill('Row reviewers')
  await page.getByLabel('Backend: Access', { exact: true }).check()
  const toggle = page.getByRole('checkbox', { name: 'All permissions for Pages', exact: true })
  const checkboxes = page.locator('input[name^="permissions[brando.pages."]')
  await expect(toggle).toHaveAttribute('aria-checked', 'false')
  await toggle.click()
  await expect(toggle).toHaveAttribute('aria-checked', 'true')
  await expect(page.locator('input[name^="permissions[brando.pages."]:checked')).toHaveCount(await checkboxes.count())
  await page.getByLabel('Pages: Edit', { exact: true }).uncheck()
  await expect(toggle).toHaveAttribute('aria-checked', 'mixed')
  await toggle.focus()
  await page.keyboard.press('Space')
  await expect(toggle).toHaveAttribute('aria-checked', 'true')
  await toggle.click()
  await expect(page.locator('input[name^="permissions[brando.pages."]:checked')).toHaveCount(0)
  await expect(page.getByLabel('Backend: Access', { exact: true })).toBeChecked()

  await page.getByLabel('Find a permission', { exact: true }).fill('View')
  await expect(page.getByLabel('Pages: Edit', { exact: true })).toHaveCount(0)
  await toggle.click()
  await page.getByLabel('Find a permission', { exact: true }).fill('')
  await expect(toggle).toHaveAttribute('aria-checked', 'mixed')
  await expect(page.getByLabel('Pages: View', { exact: true })).toBeChecked()
  await expect(page.getByLabel('Pages: Publish', { exact: true })).not.toBeChecked()
  await page.getByRole('button', { name: 'Review changes', exact: true }).click()
  await expect(page.locator('.authorization-review')).toContainText('2 permissions added')
  await page.getByRole('button', { name: 'Confirm & save' }).click()
  await expect(page.getByRole('status')).toContainText('Group saved')
})

for (const role of ['reader', 'author', 'publisher', 'none']) {
  test(`${role} gets the expected routes and cannot forge listing mutations`, async ({ page, secondUserPage, sandboxUserAgent }) => {
    const response = await fetch(e2eUrl(`/e2e/authorization/${role}`), { method: 'POST', headers: { 'user-agent': sandboxUserAgent } })
    expect(response.ok, await response.text()).toBe(true)
    await secondUserPage.goto('/admin/pages')
    if (role === 'none') {
      await expect(secondUserPage).toHaveURL('/admin/access-denied')
      return
    }
    await syncLV(secondUserPage)
    await expect(secondUserPage.getByRole('link', { name: 'Permissions', exact: true })).toHaveCount(0)
    const create = secondUserPage.getByRole('link', { name: 'Create page', exact: true })
    if (role === 'author') await expect(create).toBeVisible()
    else await expect(create).toHaveCount(0)

    // Send the same public LiveView event a forged browser could send.
    await secondUserPage.evaluate(() => {
      window.liveSocket.main.channel.push('event', { type: 'click', event: 'delete_entry', value: { id: '1' } })
    })
    await syncLV(secondUserPage)
    await page.goto('/admin/pages')
    await syncLV(page)
    await expect(page.locator('#list-row-1')).toBeVisible()

    await secondUserPage.goto('/admin/pages/update/1')
    if (role === 'reader') await expect(secondUserPage).toHaveURL('/admin/access-denied')
    else {
      await syncLV(secondUserPage)
      await expect(secondUserPage.getByTestId('submit')).toBeVisible()
    }
    await secondUserPage.goto('/admin/users')
    await expect(secondUserPage).toHaveURL('/admin/access-denied')
  })
}


test('creates an expiring shared preview through the authorized editor flow', async ({ page }) => {
  await page.goto('/admin/pages/update/1')
  await syncLV(page)
  await page.getByRole('button', { name: 'Share preview', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Get shareable link' })
  await expect(dialog).toBeVisible()
  const url = await dialog.getByRole('link', { name: 'OPEN LINK' }).getAttribute('href')
  const response = await page.request.get(url)
  expect(response.status()).toBe(200)
  expect(await response.text()).toContain('Welcome to Brando!')
})
