spark_locals_without_parens = [
  action: 0,
  action: 1,
  after_save: 1,
  alert: 1,
  alert: 2,
  alert: 3,
  align: 1,
  assign: 2,
  assign: 3,
  assigns: 1,
  blocks: 1,
  blocks: 2,
  blocks: 3,
  cardinality: 1,
  child_listing: 0,
  child_listing: 1,
  component: 1,
  confirm: 1,
  content: 1,
  datasource: 1,
  datasource: 2,
  default: 1,
  default_actions: 1,
  default_params: 1,
  description: 1,
  event: 1,
  export: 1,
  export: 2,
  field: 2,
  field: 3,
  field: 4,
  fields: 1,
  fieldset: 0,
  fieldset: 1,
  filter: 0,
  filter: 1,
  form: 0,
  form: 1,
  form: 2,
  get: 1,
  input: 2,
  input: 3,
  input: 4,
  inputs_for: 1,
  inputs_for: 2,
  instructions: 1,
  json_ld_schema: 1,
  json_ld_schema: 2,
  label: 1,
  layout: 1,
  limit: 1,
  list: 1,
  listing: 0,
  listing: 1,
  listing: 2,
  meta_schema: 0,
  meta_schema: 1,
  mutate_data: 1,
  name: 1,
  opts: 1,
  order: 1,
  preview_target: 1,
  preview_target: 2,
  query: 1,
  reassign_on_change: 1,
  redirect_on_save: 1,
  rerender_on_change: 1,
  schema: 1,
  schema_preloads: 1,
  selection_action: 0,
  selection_action: 1,
  shaded: 1,
  size: 1,
  sort: 1,
  sort: 2,
  sortable: 1,
  style: 1,
  tab: 1,
  tab: 2,
  template: 1,
  template_css_classes: 1,
  template_prop: 1,
  template_section: 1,
  type: 1,
  value_fn: 1
]

locals_without_parens = [
  absolute_url: 1,
  identifier: 1,
  persist_identifier: 1,
  meta: 2,
  sequence: 2,
  villain: 1,
  datasource: 2,
  datasources: 1,
  query: 3,
  has_image_field: 2,
  can: 2,
  can: 3,
  cannot: 2,
  cannot: 3,
  rules: 2,
  merge: 1,
  many: 2,
  list: 2,
  selection: 3,
  single: 2,
  mutation: 2,
  mutation: 3,
  # live preview
  render_path: 1,
  schema_module: 1,
  # blueprints
  application: 1,
  domain: 1,
  factory: 1,
  import_forms: 1,
  import_listings: 1,
  listings: 1,
  singular: 1,
  plural: 1,
  trait: 1,
  trait: 2,
  t: 2,
  attribute: 2,
  attribute: 3,
  relation: 2,
  relation: 3,
  extra_field: 3,
  placeholder: 1,
  translate: 2,
  table: 1,
  primary_key: 1,
  data_layer: 1,
  assets: 1,
  asset: 2,
  asset: 3,
  form_query: 1,
  subform: 3,
  subform_many: 3,
  field: 1,
  template: 2,
  listing_query: 1,
  filters: 1,
  actions: 1,
  selection_actions: 1,
  menu_item: 1,
  menu_item: 2,
  menu_subitem: 1,
  menu_subitem: 2,
  input: 1,
  inputs_for: 3,
  fieldset: 2,
  meta_schema: 2,
  json_ld_schema: 3,
  filter: 2,
  instruction: 2,
  redirect_on_save: 2,
  fieldset: 3,
  shaded: 2,
  size: 2,
  style: 2,
  type: 2
]

[
  locals_without_parens: locals_without_parens ++ spark_locals_without_parens,
  export: [locals_without_parens: locals_without_parens ++ spark_locals_without_parens],
  import_deps: [:ecto, :ecto_sql, :phoenix, :plug, :phoenix_html, :spark],
  plugins: [Phoenix.LiveView.HTMLFormatter, Spark.Formatter],
  inputs: [
    "{mix,.formatter}.exs",
    "priv/*/seeds.exs",
    "{config,lib,test,e2e}/**/*.{ex,exs,heex}"
  ],
  subdirectories: ["priv/*/migrations", "priv/templates/brando.upgrade/migrations"]
]
