language: elixir
elixir: 1.9.1
addons:
  postgresql: "9.4"
otp_release:
  - 22.0
sudo: false
env:
  global:
    - ELIXIR_ASSERT_TIMEOUT=2000
before_script:
  - mix local.hex --force
  - mix deps.get --only test
script:
  - mix test
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
  - "MIX_ENV=test mix compile && MIX_ENV=test mix coveralls.travis"
notifications:
  recipients:
    - trond@twined.net

# Handle git submodules yourself
git:
  submodules: false

# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive