language: elixir
elixir: 1.7
addons:
  postgresql: "9.4"
otp_release:
  - 20.1
sudo: false
env:
  global:
    - ELIXIR_ASSERT_TIMEOUT=2000
before_script:
  - mix local.hex --force
  - mix deps.get --only test
script:
  - mix test
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
  - "MIX_ENV=test mix compile && MIX_ENV=test mix coveralls.travis"
notifications:
  recipients:
    - trond@twined.net
