language: erlang
addons:
  postgresql: "9.4"
otp_release:
  - 18.1
sudo: false
before_install:
  - wget http://s3.hex.pm/builds/elixir/v1.1.0.zip
  - unzip -d elixir v1.1.0.zip
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - mix local.hex --force
  - mix deps.get --only test
script:
  - mix test
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
  - "MIX_ENV=test mix compile && MIX_ENV=test mix coveralls.travis"
notifications:
  recipients:
    - trond@twined.net
