defmodule Brando.Sites.Countries do
  @moduledoc """
  ISO 3166-1 alpha-2 country codes with English and Norwegian names, for the
  identity form's country select. The stored value is the code, which is what
  schema.org's `addressCountry` expects.

  Names come from CLDR (via `Intl.DisplayNames`); the list is sorted by the
  Norwegian name, the English list is sorted at compile time.
  """

  @countries [
    {"AF", "Afghanistan", "Afghanistan"},
    {"AL", "Albania", "Albania"},
    {"DZ", "Algeria", "Algerie"},
    {"AS", "American Samoa", "Amerikansk Samoa"},
    {"AD", "Andorra", "Andorra"},
    {"AO", "Angola", "Angola"},
    {"AI", "Anguilla", "Anguilla"},
    {"AQ", "Antarctica", "Antarktis"},
    {"AG", "Antigua & Barbuda", "Antigua og Barbuda"},
    {"AR", "Argentina", "Argentina"},
    {"AM", "Armenia", "Armenia"},
    {"AW", "Aruba", "Aruba"},
    {"AZ", "Azerbaijan", "Aserbajdsjan"},
    {"AU", "Australia", "Australia"},
    {"BS", "Bahamas", "Bahamas"},
    {"BH", "Bahrain", "Bahrain"},
    {"BD", "Bangladesh", "Bangladesh"},
    {"BB", "Barbados", "Barbados"},
    {"BY", "Belarus", "Belarus"},
    {"BE", "Belgium", "Belgia"},
    {"BZ", "Belize", "Belize"},
    {"BJ", "Benin", "Benin"},
    {"BM", "Bermuda", "Bermuda"},
    {"BT", "Bhutan", "Bhutan"},
    {"BO", "Bolivia", "Bolivia"},
    {"BA", "Bosnia & Herzegovina", "Bosnia-Hercegovina"},
    {"BW", "Botswana", "Botswana"},
    {"BV", "Bouvet Island", "Bouvetøya"},
    {"BR", "Brazil", "Brasil"},
    {"BN", "Brunei", "Brunei"},
    {"BG", "Bulgaria", "Bulgaria"},
    {"BF", "Burkina Faso", "Burkina Faso"},
    {"BI", "Burundi", "Burundi"},
    {"CA", "Canada", "Canada"},
    {"KY", "Cayman Islands", "Caymanøyene"},
    {"CL", "Chile", "Chile"},
    {"CX", "Christmas Island", "Christmasøya"},
    {"CO", "Colombia", "Colombia"},
    {"CK", "Cook Islands", "Cookøyene"},
    {"CR", "Costa Rica", "Costa Rica"},
    {"CU", "Cuba", "Cuba"},
    {"CW", "Curaçao", "Curaçao"},
    {"DK", "Denmark", "Danmark"},
    {"VI", "U.S. Virgin Islands", "De amerikanske jomfruøyene"},
    {"VG", "British Virgin Islands", "De britiske jomfruøyene"},
    {"AE", "United Arab Emirates", "De forente arabiske emirater"},
    {"TF", "French Southern Territories", "De franske sørterritorier"},
    {"DO", "Dominican Republic", "Den dominikanske republikk"},
    {"CF", "Central African Republic", "Den sentralafrikanske republikk"},
    {"IO", "British Indian Ocean Territory", "Det britiske territoriet i Indiahavet"},
    {"PS", "Palestinian Territories", "Det palestinske området"},
    {"DJ", "Djibouti", "Djibouti"},
    {"DM", "Dominica", "Dominica"},
    {"EC", "Ecuador", "Ecuador"},
    {"EG", "Egypt", "Egypt"},
    {"GQ", "Equatorial Guinea", "Ekvatorial-Guinea"},
    {"SV", "El Salvador", "El Salvador"},
    {"CI", "Côte d’Ivoire", "Elfenbenskysten"},
    {"ER", "Eritrea", "Eritrea"},
    {"EE", "Estonia", "Estland"},
    {"SZ", "Eswatini", "Eswatini"},
    {"ET", "Ethiopia", "Etiopia"},
    {"FK", "Falkland Islands", "Falklandsøyene"},
    {"FJ", "Fiji", "Fiji"},
    {"PH", "Philippines", "Filippinene"},
    {"FI", "Finland", "Finland"},
    {"FR", "France", "Frankrike"},
    {"GF", "French Guiana", "Fransk Guyana"},
    {"PF", "French Polynesia", "Fransk Polynesia"},
    {"FO", "Faroe Islands", "Færøyene"},
    {"GA", "Gabon", "Gabon"},
    {"GM", "Gambia", "Gambia"},
    {"GE", "Georgia", "Georgia"},
    {"GH", "Ghana", "Ghana"},
    {"GI", "Gibraltar", "Gibraltar"},
    {"GD", "Grenada", "Grenada"},
    {"GL", "Greenland", "Grønland"},
    {"GP", "Guadeloupe", "Guadeloupe"},
    {"GU", "Guam", "Guam"},
    {"GT", "Guatemala", "Guatemala"},
    {"GG", "Guernsey", "Guernsey"},
    {"GN", "Guinea", "Guinea"},
    {"GW", "Guinea-Bissau", "Guinea-Bissau"},
    {"GY", "Guyana", "Guyana"},
    {"HT", "Haiti", "Haiti"},
    {"HM", "Heard & McDonald Islands", "Heard- og McDonaldøyene"},
    {"GR", "Greece", "Hellas"},
    {"HN", "Honduras", "Honduras"},
    {"HK", "Hong Kong SAR China", "Hongkong SAR Kina"},
    {"IN", "India", "India"},
    {"ID", "Indonesia", "Indonesia"},
    {"IQ", "Iraq", "Irak"},
    {"IR", "Iran", "Iran"},
    {"IE", "Ireland", "Irland"},
    {"IS", "Iceland", "Island"},
    {"IL", "Israel", "Israel"},
    {"IT", "Italy", "Italia"},
    {"JM", "Jamaica", "Jamaica"},
    {"JP", "Japan", "Japan"},
    {"YE", "Yemen", "Jemen"},
    {"JE", "Jersey", "Jersey"},
    {"JO", "Jordan", "Jordan"},
    {"KH", "Cambodia", "Kambodsja"},
    {"CM", "Cameroon", "Kamerun"},
    {"CV", "Cape Verde", "Kapp Verde"},
    {"BQ", "Caribbean Netherlands", "Karibisk Nederland"},
    {"KZ", "Kazakhstan", "Kasakhstan"},
    {"KE", "Kenya", "Kenya"},
    {"CN", "China", "Kina"},
    {"KG", "Kyrgyzstan", "Kirgisistan"},
    {"KI", "Kiribati", "Kiribati"},
    {"CC", "Cocos (Keeling) Islands", "Kokosøyene"},
    {"KM", "Comoros", "Komorene"},
    {"CD", "Congo - Kinshasa", "Kongo"},
    {"CG", "Congo - Brazzaville", "Kongo-Brazzaville"},
    {"XK", "Kosovo", "Kosovo"},
    {"HR", "Croatia", "Kroatia"},
    {"KW", "Kuwait", "Kuwait"},
    {"CY", "Cyprus", "Kypros"},
    {"LA", "Laos", "Laos"},
    {"LV", "Latvia", "Latvia"},
    {"LS", "Lesotho", "Lesotho"},
    {"LB", "Lebanon", "Libanon"},
    {"LR", "Liberia", "Liberia"},
    {"LY", "Libya", "Libya"},
    {"LI", "Liechtenstein", "Liechtenstein"},
    {"LT", "Lithuania", "Litauen"},
    {"LU", "Luxembourg", "Luxemburg"},
    {"MO", "Macao SAR China", "Macao SAR Kina"},
    {"MG", "Madagascar", "Madagaskar"},
    {"MW", "Malawi", "Malawi"},
    {"MY", "Malaysia", "Malaysia"},
    {"MV", "Maldives", "Maldivene"},
    {"ML", "Mali", "Mali"},
    {"MT", "Malta", "Malta"},
    {"IM", "Isle of Man", "Man"},
    {"MA", "Morocco", "Marokko"},
    {"MH", "Marshall Islands", "Marshalløyene"},
    {"MQ", "Martinique", "Martinique"},
    {"MR", "Mauritania", "Mauritania"},
    {"MU", "Mauritius", "Mauritius"},
    {"YT", "Mayotte", "Mayotte"},
    {"MX", "Mexico", "Mexico"},
    {"FM", "Micronesia", "Mikronesiaføderasjonen"},
    {"MD", "Moldova", "Moldova"},
    {"MC", "Monaco", "Monaco"},
    {"MN", "Mongolia", "Mongolia"},
    {"ME", "Montenegro", "Montenegro"},
    {"MS", "Montserrat", "Montserrat"},
    {"MZ", "Mozambique", "Mosambik"},
    {"MM", "Myanmar (Burma)", "Myanmar (Burma)"},
    {"NA", "Namibia", "Namibia"},
    {"NR", "Nauru", "Nauru"},
    {"NL", "Netherlands", "Nederland"},
    {"NP", "Nepal", "Nepal"},
    {"NZ", "New Zealand", "New Zealand"},
    {"NI", "Nicaragua", "Nicaragua"},
    {"NE", "Niger", "Niger"},
    {"NG", "Nigeria", "Nigeria"},
    {"NU", "Niue", "Niue"},
    {"KP", "North Korea", "Nord-Korea"},
    {"MK", "North Macedonia", "Nord-Makedonia"},
    {"MP", "Northern Mariana Islands", "Nord-Marianene"},
    {"NF", "Norfolk Island", "Norfolkøya"},
    {"NO", "Norway", "Norge"},
    {"NC", "New Caledonia", "Ny-Caledonia"},
    {"OM", "Oman", "Oman"},
    {"PK", "Pakistan", "Pakistan"},
    {"PW", "Palau", "Palau"},
    {"PA", "Panama", "Panama"},
    {"PG", "Papua New Guinea", "Papua Ny-Guinea"},
    {"PY", "Paraguay", "Paraguay"},
    {"PE", "Peru", "Peru"},
    {"PN", "Pitcairn Islands", "Pitcairnøyene"},
    {"PL", "Poland", "Polen"},
    {"PT", "Portugal", "Portugal"},
    {"PR", "Puerto Rico", "Puerto Rico"},
    {"QA", "Qatar", "Qatar"},
    {"RE", "Réunion", "Réunion"},
    {"RO", "Romania", "Romania"},
    {"RU", "Russia", "Russland"},
    {"RW", "Rwanda", "Rwanda"},
    {"KN", "St. Kitts & Nevis", "Saint Kitts og Nevis"},
    {"BL", "St. Barthélemy", "Saint-Barthélemy"},
    {"MF", "St. Martin", "Saint-Martin"},
    {"PM", "St. Pierre & Miquelon", "Saint-Pierre-et-Miquelon"},
    {"SB", "Solomon Islands", "Salomonøyene"},
    {"WS", "Samoa", "Samoa"},
    {"SM", "San Marino", "San Marino"},
    {"ST", "São Tomé & Príncipe", "São Tomé og Príncipe"},
    {"SA", "Saudi Arabia", "Saudi-Arabia"},
    {"SN", "Senegal", "Senegal"},
    {"RS", "Serbia", "Serbia"},
    {"SC", "Seychelles", "Seychellene"},
    {"SL", "Sierra Leone", "Sierra Leone"},
    {"SG", "Singapore", "Singapore"},
    {"SX", "Sint Maarten", "Sint Maarten"},
    {"SK", "Slovakia", "Slovakia"},
    {"SI", "Slovenia", "Slovenia"},
    {"SO", "Somalia", "Somalia"},
    {"ES", "Spain", "Spania"},
    {"LK", "Sri Lanka", "Sri Lanka"},
    {"SH", "St. Helena", "St. Helena"},
    {"LC", "St. Lucia", "St. Lucia"},
    {"VC", "St. Vincent & Grenadines", "St. Vincent og Grenadinene"},
    {"GB", "United Kingdom", "Storbritannia"},
    {"SD", "Sudan", "Sudan"},
    {"SR", "Suriname", "Surinam"},
    {"SJ", "Svalbard & Jan Mayen", "Svalbard og Jan Mayen"},
    {"CH", "Switzerland", "Sveits"},
    {"SE", "Sweden", "Sverige"},
    {"SY", "Syria", "Syria"},
    {"ZA", "South Africa", "Sør-Afrika"},
    {"GS", "South Georgia & South Sandwich Islands", "Sør-Georgia og Sør-Sandwichøyene"},
    {"KR", "South Korea", "Sør-Korea"},
    {"SS", "South Sudan", "Sør-Sudan"},
    {"TJ", "Tajikistan", "Tadsjikistan"},
    {"TW", "Taiwan", "Taiwan"},
    {"TZ", "Tanzania", "Tanzania"},
    {"TH", "Thailand", "Thailand"},
    {"TG", "Togo", "Togo"},
    {"TK", "Tokelau", "Tokelau"},
    {"TO", "Tonga", "Tonga"},
    {"TT", "Trinidad & Tobago", "Trinidad og Tobago"},
    {"TD", "Chad", "Tsjad"},
    {"CZ", "Czechia", "Tsjekkia"},
    {"TN", "Tunisia", "Tunisia"},
    {"TM", "Turkmenistan", "Turkmenistan"},
    {"TC", "Turks & Caicos Islands", "Turks- og Caicosøyene"},
    {"TV", "Tuvalu", "Tuvalu"},
    {"TR", "Türkiye", "Tyrkia"},
    {"DE", "Germany", "Tyskland"},
    {"UG", "Uganda", "Uganda"},
    {"UA", "Ukraine", "Ukraina"},
    {"HU", "Hungary", "Ungarn"},
    {"UY", "Uruguay", "Uruguay"},
    {"US", "United States", "USA"},
    {"UM", "U.S. Outlying Islands", "USAs ytre øyer"},
    {"UZ", "Uzbekistan", "Usbekistan"},
    {"VU", "Vanuatu", "Vanuatu"},
    {"VA", "Vatican City", "Vatikanstaten"},
    {"VE", "Venezuela", "Venezuela"},
    {"EH", "Western Sahara", "Vest-Sahara"},
    {"VN", "Vietnam", "Vietnam"},
    {"WF", "Wallis & Futuna", "Wallis og Futuna"},
    {"ZM", "Zambia", "Zambia"},
    {"ZW", "Zimbabwe", "Zimbabwe"},
    {"TL", "Timor-Leste", "Øst-Timor"},
    {"AT", "Austria", "Østerrike"},
    {"AX", "Åland Islands", "Åland"}
  ]

  @by_english Enum.sort_by(@countries, &elem(&1, 1))
  @codes MapSet.new(@countries, &elem(&1, 0))

  @doc """
  Select options in the admin's locale. A stored value that isn't a known code
  (typed before this was a select) is kept as the first option so it isn't lost.
  """
  def options(form, _opts) do
    options =
      Enum.map(countries_for_locale(Gettext.get_locale()), fn {code, name} ->
        %{value: code, label: name}
      end)

    case form[:country] && form[:country].value do
      value when is_binary(value) and value != "" ->
        if MapSet.member?(@codes, value),
          do: options,
          else: [%{value: value, label: value} | options]

      _ ->
        options
    end
  end

  defp countries_for_locale(locale) when locale in ["no", "nb", "nn"],
    do: Enum.map(@countries, fn {code, _en, no} -> {code, no} end)

  defp countries_for_locale(_locale),
    do: Enum.map(@by_english, fn {code, en, _no} -> {code, en} end)
end
