defmodule Brando.JSONLD.Schema.CreativeWork do
  @moduledoc """
  CreativeWork schema
  """
  @derive Jason.Encoder
  defstruct "@context": "http://schema.org",
            "@type": "CreativeWork",
            about: nil,
            abstract: nil,
            accessMode: nil,
            accessModeSufficient: nil,
            accessibilityAPI: nil,
            accessibilityControl: nil,
            accessibilityFeature: nil,
            accessibilityHazard: nil,
            accessibilitySummary: nil,
            accountablePerson: nil,
            aggregateRating: nil,
            alternativeHeadline: nil,
            associatedMedia: nil,
            audience: nil,
            audio: nil,
            author: nil,
            award: nil,
            awards: nil,
            character: nil,
            citation: nil,
            comment: nil,
            commentCount: nil,
            conditionsOfAccess: nil,
            contentLocation: nil,
            contentRating: nil,
            contentReferenceTime: nil,
            contributor: nil,
            copyrightHolder: nil,
            copyrightNotice: nil,
            copyrightYear: nil,
            correction: nil,
            creativeWorkStatus: nil,
            creator: nil,
            dateCreated: nil,
            dateModified: nil,
            datePublished: nil,
            discussionUrl: nil,
            editor: nil,
            educationalAlignment: nil,
            educationalLevel: nil,
            educationalUse: nil,
            encoding: nil,
            encodingFormat: nil,
            encodings: nil,
            exampleOfWork: nil,
            expires: nil,
            fileFormat: nil,
            funder: nil,
            funding: nil,
            genre: nil,
            hasPart: nil,
            headline: nil,
            identifier: nil,
            image: nil,
            inLanguage: nil,
            interactionStatistic: nil,
            interactivityType: nil,
            interpretedAsClaim: nil,
            isAccessibleForFree: nil,
            isBasedOn: nil,
            isBasedOnUrl: nil,
            isFamilyFriendly: nil,
            isPartOf: nil,
            keywords: nil,
            learningResourceType: nil,
            license: nil,
            locationCreated: nil,
            mainEntity: nil,
            mainEntityOfPage: nil,
            material: nil,
            materialExtent: nil,
            mentions: nil,
            name: nil,
            offers: nil,
            position: nil,
            producer: nil,
            provider: nil,
            publication: nil,
            publisher: nil,
            publisherImprint: nil,
            publishingPrinciples: nil,
            recordedAt: nil,
            releasedEvent: nil,
            review: nil,
            reviews: nil,
            schemaVersion: nil,
            sdDatePublished: nil,
            sdLicense: nil,
            sdPublisher: nil,
            size: nil,
            sourceOrganization: nil,
            spatial: nil,
            spatialCoverage: nil,
            sponsor: nil,
            subjectOf: nil,
            teaches: nil,
            temporal: nil,
            temporalCoverage: nil,
            text: nil,
            thumbnailUrl: nil,
            timeRequired: nil,
            translator: nil,
            typicalAgeRange: nil,
            url: nil,
            usageInfo: nil,
            version: nil,
            video: nil,
            workExample: nil

  def build(work) do
    require Logger

    Logger.error("""
    => JSONLD/Schema >> CreativeWork
    #{inspect(work, pretty: true)}
    """)

    %__MODULE__{}
  end
end
