import { test, expect } from '../test-support/setupAuth'
import { syncLV } from '../utils'

test.beforeEach(async ({ page }) => page.setViewportSize({ width: 1440, height: 1000 }))

async function sameHeight(locators, expected) {
  for (const locator of locators) {
    await expect(locator).toBeVisible()
    expect((await locator.boundingBox()).height).toBeCloseTo(expected, 0)
  }
}

async function noOverflow(page) {
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(0)
}

test('listing filters align, disclose children by keyboard and retain creators on mobile', async ({ page }, testInfo) => {
  expect((await page.request.post('/e2e/admin-workspace-fixtures')).ok()).toBeTruthy()
  await page.goto('/admin/pages')
  await syncLV(page)
  const filter = page.locator('.list-tools .filter').first()
  const sort = page.locator('.sorts .simple-dropdown-button')
  await sameHeight([filter, sort], 38)
  expect((await filter.boundingBox()).y).toBeCloseTo((await sort.boundingBox()).y, 0)
  for (const status of await page.locator('.statuses button').all()) {
    const circle = await status.locator('svg').boundingBox()
    await expect(status.locator('.label')).toBeVisible()
    expect(circle.height).toBeGreaterThanOrEqual(parseFloat(await status.evaluate(e => getComputedStyle(e).fontSize)))
  }
  // Optical alignment follows visible glyphs, not the label's line-box center.
  await page.locator('.statuses').screenshot({ path: testInfo.outputPath('status-alignment-desktop.png') })
  const home = page.locator('.listing-home [data-icon]')
  await expect(home).toBeVisible()
  expect(await home.evaluate(e => getComputedStyle(e).maskImage)).not.toBe('none')
  const childButton = page.getByTestId('children-button').filter({ visible: true }).first()
  await childButton.focus()
  await page.keyboard.press('Enter')
  await expect(childButton).toHaveAttribute('aria-expanded', 'true')
  await expect(page.locator('.child-row').first()).toBeVisible()
  const count = await childButton.locator('.children-number').boundingBox()
  const chevron = await childButton.locator('[data-icon]').boundingBox()
  expect(count.y + count.height / 2).toBeCloseTo(chevron.y + chevron.height / 2, 0)
  await page.screenshot({ path: testInfo.outputPath('pages-expanded-desktop.png'), fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await noOverflow(page)
  await expect(page.locator('.main-content .listing-creator .avatar').first()).toBeVisible()
  await expect(page.locator('.child-row .listing-creator .avatar').first()).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('pages-expanded-mobile.png'), fullPage: true })
})

test('menu controls align, keyboard status works and save follows the items', async ({ page }, testInfo) => {
  await page.goto('/admin/config/navigation/menus/update/1')
  await syncLV(page)
  await page.locator('.form-content > .form-tabs').screenshot({ path: testInfo.outputPath('single-tab-toolbar-desktop.png') })
  const status = page.locator('#menu_status-field-wrapper')
  await sameHeight([page.locator('#menu_title'), page.locator('#menu_key'), status.locator('.multiselect'), page.locator('#menu_language-field-wrapper .multiselect')], 40)
  const row = page.locator('.subform-entry').first()
  const fields = [row.locator('.radios-wrapper.status.compact').first(), page.locator('#menu_items_0_key'), row.locator('.link-preview').first()]
  await sameHeight(fields, 40)
  const labels = await row.locator('.subform-fields > .brando-input').evaluateAll(inputs => inputs.map(input => input.querySelector('.label-wrapper').getBoundingClientRect().y))
  expect(Math.max(...labels) - Math.min(...labels)).toBeLessThanOrEqual(1)
  const compactTrigger = row.locator('.status-trigger').first()
  await compactTrigger.focus()
  await page.keyboard.press('Space')
  await expect(compactTrigger).toHaveAttribute('aria-expanded', 'true')
  await expect(page.locator('#status-dropdown-menu_items_0_status')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(compactTrigger).toBeFocused()
  await expect(compactTrigger).toHaveAttribute('aria-expanded', 'false')
  await status.getByRole('button', { name: 'Select', exact: true }).press('Enter')
  await status.getByRole('button', { name: 'Draft', exact: true }).press('Enter')
  await expect(status.locator('.select-label')).toHaveText('Draft')
  const save = await page.getByTestId('submit').boundingBox()
  const items = await page.locator('.subform').first().boundingBox()
  expect(save.y - items.y - items.height).toBeCloseTo(24, 0)
  await page.screenshot({ path: testInfo.outputPath('menu-editor-desktop.png'), fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await noOverflow(page)
  await expect(page.locator('#menu_items_1_key-field-wrapper label')).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('menu-editor-mobile.png'), fullPage: true })
  await page.getByTestId('submit').click()
  await expect(page).toHaveURL('/admin/config/navigation/menus')
  await page.goto('/admin/config/navigation/menus/update/1')
  await syncLV(page)
  await expect(status.locator('.select-label')).toHaveText('Draft')
})

test('page text and select controls match and toolbar dropdown chevrons are identical', async ({ page }, testInfo) => {
  await page.goto('/admin/pages/update/1')
  await syncLV(page)
  await sameHeight([page.locator('#page_title'), page.locator('#page_uri'), page.locator('.multiselect').filter({ visible: true }).first()], 44)
  const preview = page.locator('.preview-chooser-trigger')
  const saveDropdown = page.getByTestId('split-dropdown-button')
  const previewIcon = preview.locator('.dropdown-chevron')
  const saveIcon = saveDropdown.locator('.dropdown-chevron')
  await sameHeight([previewIcon, saveIcon], 14)
  expect(await previewIcon.evaluate(e => getComputedStyle(e).maskImage)).toBe(await saveIcon.evaluate(e => getComputedStyle(e).maskImage))
  await preview.focus()
  await page.keyboard.press('Enter')
  await expect(page.locator('.preview-choices')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(preview).toBeFocused()
  await expect(page.locator('.preview-choices')).toHaveCount(0)
  await expect(page.locator('#page_language-field-wrapper .button-edit')).toHaveText('Select')
  await page.locator('#page_language-field-wrapper .button-edit').press('Enter')
  await expect(page.getByRole('dialog', { name: 'Select option' })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.locator('#page_language-field-wrapper .button-edit')).toHaveText('Select')
  await saveDropdown.press('Enter')
  await expect(page.getByTestId('split-dropdown-content')).toBeVisible()
  await saveDropdown.press('Enter')
  await page.screenshot({ path: testInfo.outputPath('page-editor-desktop.png'), fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await noOverflow(page)
  await page.screenshot({ path: testInfo.outputPath('page-editor-mobile.png'), fullPage: true })
})
