import { test, expect } from '../../test-support/setupAuth'
import { syncLV } from '../../utils'
import { execFileSync } from 'node:child_process'
import { readFile } from 'node:fs/promises'
import path from 'node:path'

// Use Python's standard ZIP library so the browser consumes an independently
// produced archive, rather than an archive generated by the implementation.
function zipSource(source) {
  return execFileSync('python3', ['-c', `
import io, sys, zipfile
out = io.BytesIO()
with zipfile.ZipFile(out, 'w', zipfile.ZIP_DEFLATED) as z:
    z.writestr('hero.exs', sys.argv[1])
sys.stdout.buffer.write(out.getvalue())
`, source])
}

function editZip(binary, before, after) {
  return execFileSync('python3', ['-c', `
import io, sys, zipfile
out = io.BytesIO()
with zipfile.ZipFile(io.BytesIO(sys.stdin.buffer.read())) as original:
    with zipfile.ZipFile(out, 'w', zipfile.ZIP_DEFLATED) as updated:
        for name in original.namelist():
            body = original.read(name)
            if name.endswith('.exs'):
                body = body.replace(sys.argv[1].encode(), sys.argv[2].encode())
            updated.writestr(name, body)
sys.stdout.buffer.write(out.getvalue())
`, before, after], { input: binary })
}

async function fixtureZip() {
  const file = path.resolve(__dirname, '../../../../../test/fixtures/definitions/hero.exs.txt')
  const source = (await readFile(file, 'utf8'))
    .replace('uid "hero-test"', 'uid "admin-files-hero"')
    .replace('"Hero"', '"DSL Hero"')
  return zipSource(source)
}

async function openFiles(page) {
  await page.goto('/admin/config/content/modules')
  await page.getByRole('button', { name: 'Import / export DSL', exact: true }).click()
  await expect(page.locator('#module-files-modal')).toBeVisible()
  await syncLV(page)
  return page.locator('#module-files-modal')
}

async function preview(page, binary) {
  await page.locator('#module-files-import-form input[type=file]').setInputFiles({
    name: 'modules.zip', mimeType: 'application/zip', buffer: binary,
  })
  await page.getByRole('button', { name: 'Preview import', exact: true }).click()
  await expect(page.locator('#module-files-preview')).toBeVisible()
}

async function download(page, selector) {
  const waiting = page.waitForEvent('download')
  await page.locator(selector).click()
  const file = await waiting
  return readFile(await file.path())
}

async function apply(page) {
  await page.getByRole('button', { name: 'Apply import', exact: true }).click()
  await expect(page.locator('#module-files-result')).toContainText('Import complete')
  return download(page, '#module-files-updated-download')
}

async function reset(page) {
  await page.getByRole('button', { name: 'Back to import / export', exact: true }).click()
  await expect(page.locator('#module-files-import-form')).toBeVisible()
}

test('export and import DSL bundles with review, updated baselines and responsive controls', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 1440, height: 1100 })
  const modal = await openFiles(page)
  await expect(page.getByRole('button', { name: 'Preview import', exact: true })).toBeDisabled()
  await page.screenshot({ path: testInfo.outputPath('module-files-desktop.png') })
  await preview(page, await fixtureZip())
  await expect(page.locator('.module-files-counts')).toContainText('Create: 1')
  await page.getByRole('button', { name: 'Cancel preview', exact: true }).click()
  await expect(page.locator('#module-files-preview')).toHaveCount(0)
  await preview(page, await fixtureZip())
  let bundle = await apply(page)
  await expect(page.locator('#module-files-result')).toContainText('1 definition changed.')
  await reset(page)

  await page.getByRole('button', { name: 'Prepare export', exact: true }).click()
  const exported = await download(page, '#module-files-download')
  expect(exported.subarray(0, 2).toString()).toBe('PK')
  await preview(page, exported)
  await expect(page.locator('.module-files-counts .module-files-badge')).toHaveCount(1)
  await expect(page.locator('.module-files-counts')).toContainText('Unchanged:')
  await page.getByRole('button', { name: 'Cancel preview', exact: true }).click()

  bundle = editZip(bundle, 'class "hero"', 'class "hero--updated"')
  await preview(page, bundle)
  await expect(page.locator('.module-files-counts')).toContainText('Update: 1')
  await page.locator('.module-files-change > summary').click()
  await expect(page.locator('.module-files-diff')).toContainText('hero--updated')
  await expect(page.locator('.module-files-preview')).toContainText('Nothing has been applied')
  await page.screenshot({ path: testInfo.outputPath('module-files-review.png') })
  bundle = await apply(page)
  await page.screenshot({ path: testInfo.outputPath('module-files-complete.png') })
  await reset(page)
  await preview(page, bundle)
  await expect(page.locator('.module-files-counts')).toContainText('Unchanged: 1')
  await apply(page)
  await expect(page.locator('#module-files-result')).toContainText('0 definitions changed.')
  await reset(page)

  await page.setViewportSize({ width: 390, height: 844 })
  await modal.getByRole('heading', { name: 'Import definitions', exact: true }).scrollIntoViewIfNeeded()
  await expect(page.locator('#module-files-import-form')).toBeVisible()
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
  await page.screenshot({ path: testInfo.outputPath('module-files-mobile.png') })
})

test('rejects malformed files and prevents a stale admin preview from overwriting changes', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 1440, height: 1100 })
  await openFiles(page)
  await page.locator('#module-files-import-form input[type=file]').setInputFiles({
    name: 'broken.zip', mimeType: 'application/zip', buffer: Buffer.from('invalid'),
  })
  await page.getByRole('button', { name: 'Preview import', exact: true }).click()
  await expect(page.locator('#module-files [role=alert]')).toContainText('expected a valid ZIP')
  await preview(page, await fixtureZip())
  let bundle = await apply(page)
  await reset(page)
  bundle = editZip(bundle, 'class "hero"', 'class "from-files"')
  await preview(page, bundle)

  const editor = await page.context().newPage()
  await editor.goto('/admin/config/content/modules')
  await editor.getByRole('link', { name: 'DSL Hero', exact: true }).click()
  await syncLV(editor)
  const overview = editor.getByRole('tab', { name: /^Overview/ })
  await expect(async () => {
    await overview.click()
    await expect(overview).toHaveAttribute('aria-selected', 'true')
  }).toPass()
  await editor.locator('input[name="module[class]"]').fill('admin-change')
  await editor.getByTestId('submit').click()
  await expect(editor).toHaveURL('/admin/config/content/modules')

  await page.getByRole('button', { name: 'Apply import', exact: true }).click()
  await expect(page.locator('#module-files [role=alert]')).toContainText('target changed')
  await expect(page.locator('#module-files-import-form')).toBeVisible()
  await page.getByRole('button', { name: 'Preview import', exact: true }).click()
  await expect(page.locator('.module-files-counts')).toContainText('Conflict: 1')
  await expect(page.getByRole('button', { name: 'Apply import', exact: true })).toBeDisabled()
  await page.screenshot({ path: testInfo.outputPath('module-files-conflict.png') })
  await editor.getByRole('link', { name: 'DSL Hero', exact: true }).click()
  await syncLV(editor)
  await expect(editor.locator('input[name="module[class]"]')).toHaveValue('admin-change')
  await editor.close()
})
