import { test, expect } from '../../test-support/setupAuth'
import { syncLV } from '../../utils'

test.describe('Entry recovery copies', () => {
  test.setTimeout(90000)

  const createDraft = async page => {
    await page.setViewportSize({ width: 1440, height: 1800 })
    await page.goto('/admin/pages/create')
    await syncLV(page)
    await page.getByLabel('Title', { exact: true }).fill('Autumn campaign')
    await page.getByLabel('URI').fill('autumn-campaign')
    await page.getByRole('button', { name: 'Add block' }).last().click()
    await page.getByRole('button', { name: '05 LIVE PREVIEW TEST' }).click()
    await page.getByRole('button', { name: 'Styled Header' }).click()
    await syncLV(page)
    const input = page.locator('.header-block textarea')
    await input.fill('A new season of ideas')
    await expect(page.getByTestId('draft-status')).toContainText('Recovery copy saved at', { timeout: 25000 })
    await expect(input).toBeFocused()
  }

  const review = async page => {
    await page.reload()
    await expect(page.getByTestId('draft-notice')).toBeVisible()
    await expect(page.getByLabel('Title', { exact: true })).toHaveValue('')
    await page.getByRole('button', { name: 'Review recovery copy', exact: true }).click()
  }

  test('browses a recovery table and keeps inspected content open across autosave patches', async ({ page }, testInfo) => {
    await createDraft(page)
    expect((await page.request.post('/e2e/drafts/history')).ok()).toBeTruthy()
    await review(page)
    const panel = page.getByTestId('draft-panel')
    const table = panel.getByRole('table', { name: 'Recovery copies', exact: true })
    const preview = panel.locator('.draft-content-preview')
    const inspector = panel.locator('.draft-raw-content')
    await expect(table.locator('tbody tr')).toHaveCount(11)
    await expect(preview).toContainText('A new season of ideas')
    await inspector.locator('summary').click()
    await expect(inspector).toHaveAttribute('open', '')

    // Wait for the actual 15-second capture to patch the same @draft assign.
    const statusBefore = await page.getByTestId('draft-status').textContent()
    await expect(page.getByTestId('draft-status')).not.toHaveText(statusBefore, { timeout: 20000 })
    await expect(inspector).toHaveAttribute('open', '')
    await expect(panel).toBeVisible()

    const otherCopy = table.getByRole('button', { name: 'Autumn campaign 1', exact: true })
    await otherCopy.focus()
    await page.keyboard.press('Enter')
    await expect(otherCopy).toHaveAttribute('aria-pressed', 'true')
    await expect(preview).toContainText('Autumn campaign 1')
    await expect(inspector).toHaveAttribute('open', '')
    await expect(inspector.locator('pre')).toContainText('Autumn campaign 1')

    await page.context().grantPermissions(['clipboard-read', 'clipboard-write'])
    await panel.getByRole('button', { name: 'Copy JSON', exact: true }).click()
    await expect(inspector.getByRole('status')).toHaveText('Copied')
    const copied = await page.evaluate(() => navigator.clipboard.readText())
    expect(JSON.parse(copied).main.title).toBe('Autumn campaign 1')
    await panel.getByRole('button', { name: 'Copy text', exact: true }).click()
    await expect(panel.getByRole('button', { name: 'Copy text', exact: true })).toHaveAttribute('data-copy-state', 'copied')
    expect(await page.evaluate(() => navigator.clipboard.readText())).toContain('A new season of ideas')
    const downloadPromise = page.waitForEvent('download')
    await panel.getByRole('link', { name: 'Download JSON', exact: true }).click()
    const download = await downloadPromise
    expect(download.suggestedFilename()).toBe('entry-recovery.json')
    const chunks = []
    for await (const chunk of await download.createReadStream()) chunks.push(chunk)
    expect(JSON.parse(Buffer.concat(chunks).toString())).toEqual(JSON.parse(copied))

    await inspector.locator('summary').click()
    await expect(inspector).not.toHaveAttribute('open', '')
    await table.getByRole('button', { name: 'Autumn campaign', exact: true }).click()
    await expect(inspector).not.toHaveAttribute('open', '')
    await panel.screenshot({ path: testInfo.outputPath('recovery-table.png'), animations: 'disabled' })
    await inspector.locator('summary').click()
    await panel.screenshot({ path: testInfo.outputPath('recovery-inspector.png'), animations: 'disabled' })
    await page.setViewportSize({ width: 390, height: 1800 })
    await expect.poll(() => panel.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
    await panel.screenshot({ path: testInfo.outputPath('recovery-table-mobile.png'), animations: 'disabled' })
  })

  test('recovers a new entry and unsaved block after reload, then resolves the copy on save', async ({ page }, testInfo) => {
    await createDraft(page)
    await review(page)
    const panel = page.getByTestId('draft-panel')
    await expect(panel.locator('.draft-comparison')).toBeVisible()
    await panel.screenshot({ path: testInfo.outputPath('recovery-available.png'), animations: 'disabled' })
    await page.setViewportSize({ width: 390, height: 1800 })
    await panel.screenshot({ path: testInfo.outputPath('recovery-compact.png'), animations: 'disabled' })
    await page.setViewportSize({ width: 1440, height: 1100 })
    await page.getByRole('button', { name: 'Restore recovery copy', exact: true }).click()
    await expect(page.getByLabel('Title', { exact: true })).toHaveValue('Autumn campaign')
    await expect(page.locator('.header-block textarea')).toHaveValue('A new season of ideas')
    await expect(page.getByTestId('draft-status')).toContainText('Recovery copy saved at', { timeout: 25000 })
    await page.screenshot({ path: testInfo.outputPath('recovery-restored.png'), fullPage: true })

    await page.getByTestId('split-dropdown-button').click()
    await page.getByRole('button', { name: /Save and continue editing/ }).click()
    await expect(page).toHaveURL(/\/update\//, { timeout: 30000 })
    // Let the periodic capture run after save-and-continue: it must not
    // manufacture another draft from differences in persisted row metadata.
    await expect(page.getByTestId('draft-status')).toContainText('Recovery copy saved at', { timeout: 20000 })
    await page.reload()
    await expect(page.getByLabel('Title', { exact: true })).toHaveValue('Autumn campaign')
    await expect(page.locator('.header-block textarea')).toHaveValue('A new season of ideas')
    await expect(page.getByTestId('draft-notice')).toHaveCount(0)
    await expect(page.getByRole('button', { name: /^Recovery copies/ })).toHaveCount(0)

    await page.getByLabel('Title', { exact: true }).fill('Autumn campaign revised')
    await page.locator('.header-block textarea').fill('An updated season of ideas')
    await expect(page.getByTestId('draft-status')).toContainText('Recovery copy saved at', { timeout: 25000 })
    await page.reload()
    await expect(page.getByLabel('Title', { exact: true })).toHaveValue('Autumn campaign')
    await page.getByRole('button', { name: 'Review recovery copy', exact: true }).click()
    await expect(page.locator('.draft-comparison')).toContainText('Autumn campaign revised')
    await page.getByRole('button', { name: 'Restore recovery copy', exact: true }).click()
    await expect(page.getByLabel('Title', { exact: true })).toHaveValue('Autumn campaign revised')
    await expect(page.locator('.header-block textarea')).toHaveValue('An updated season of ideas')
    await page.getByTestId('split-dropdown-button').click()
    await page.getByRole('button', { name: /Save and continue editing/ }).click()
    await expect(page.getByTestId('draft-panel')).toHaveCount(0)
    await expect(page.getByTestId('draft-status')).toContainText('Recovery copies are saved automatically')
    await page.reload()
    await expect(page.getByLabel('Title', { exact: true })).toHaveValue('Autumn campaign revised')
    await expect(page.locator('.header-block textarea')).toHaveValue('An updated season of ideas')
  })

  test('a failed restore survives reload without trapping the editor or overwriting the original', async ({ page }, testInfo) => {
    await createDraft(page)
    expect((await page.request.post('/e2e/drafts/unsupported')).ok()).toBeTruthy()
    await review(page)
    await page.getByRole('button', { name: 'Restore recovery copy', exact: true }).click()
    await expect(page.getByTestId('draft-panel').getByRole('alert')).toContainText('unsupported format')
    await expect(page.getByRole('button', { name: 'Restore compatible content', exact: true })).toHaveCount(0)
    await page.getByTestId('draft-panel').screenshot({ path: testInfo.outputPath('recovery-failed.png'), animations: 'disabled' })
    await page.reload()
    await expect(page.getByTestId('draft-panel')).toHaveCount(0)
    await expect(page.getByTestId('draft-notice')).toHaveCount(0)
    await page.getByRole('button', { name: /^Recovery copies/ }).click()
    await page.getByRole('button', { name: 'Start fresh', exact: true }).click()
    await expect(page.getByLabel('Title', { exact: true })).toHaveValue('')
    await expect(page.locator('.entry-block')).toHaveCount(0)
    await expect(page.getByTestId('draft-notice')).toHaveCount(0)
    await page.getByLabel('Title', { exact: true }).fill('A fresh start')
    await expect(page.getByTestId('draft-status')).toContainText('Recovery copy saved at', { timeout: 25000 })
    await page.reload()
    await page.getByRole('button', { name: /^Recovery copies/ }).click()
    await expect(page.getByTestId('draft-panel').getByRole('button', { name: /Autumn campaign/ })).toBeVisible()
    await expect(page.getByTestId('draft-panel').getByRole('button', { name: /A fresh start/ })).toBeVisible()
  })

  test('changed modules require review and retain incompatible block content', async ({ page }, testInfo) => {
    await createDraft(page)
    expect((await page.request.post('/e2e/drafts/change-module')).ok()).toBeTruthy()
    await review(page)
    await page.getByRole('button', { name: 'Restore recovery copy', exact: true }).click()
    await expect(page.getByTestId('draft-panel').getByRole('alert')).toContainText('modules that have changed')
    await expect(page.getByText('Block needs review', { exact: true })).toBeVisible()
    await page.getByText('Recover this block’s content', { exact: true }).click()
    await expect(page.locator('.draft-block-issue pre')).toContainText('A new season of ideas')
    await page.getByTestId('draft-panel').screenshot({ path: testInfo.outputPath('recovery-module-changed.png'), animations: 'disabled' })
    await page.getByRole('button', { name: 'Restore compatible content', exact: true }).click()
    await expect(page.getByLabel('Title', { exact: true })).toHaveValue('Autumn campaign')
    await expect(page.locator('.entry-block')).toHaveCount(0)
    await expect(page.locator('.draft-block-issue pre')).toContainText('A new season of ideas')
  })

  test('recovers nested child content and persists it through a subsequent save', async ({ page }) => {
    await page.goto('/admin/pages/create')
    await syncLV(page)
    await page.getByLabel('Title', { exact: true }).fill('Recovered team')
    await page.getByLabel('URI').fill('recovered-team')
    await page.getByRole('button', { name: 'Add block' }).last().click()
    await page.getByRole('button', { name: 'COPY PASTE TEST' }).click()
    await page.getByRole('button', { name: 'Team Section' }).click()
    const parent = page.locator('[data-module-multi="true"]')
    await parent.locator('.block-plus').last().click()
    await page.getByRole('button', { name: 'COPY PASTE TEST' }).click()
    await page.getByRole('button', { name: /^Team Member\b/ }).click()
    const member = parent.locator('.block-children [data-uid]').first()
    await member.locator('.block-vars').getByLabel('Name').fill('Alex')
    await member.locator('.block-vars').getByLabel('Role').fill('Editor')
    await expect(page.getByTestId('draft-status')).toContainText('Recovery copy saved at', { timeout: 25000 })
    await review(page)
    await page.getByRole('button', { name: 'Restore recovery copy', exact: true }).click()
    await expect(member.locator('.block-vars').getByLabel('Name')).toHaveValue('Alex')
    await expect(member.locator('.block-vars').getByLabel('Role')).toHaveValue('Editor')
    await page.getByTestId('split-dropdown-button').click()
    await page.getByRole('button', { name: /Save and continue editing/ }).click()
    await expect(page).toHaveURL(/\/update\//, { timeout: 30000 })
    await page.reload()
    await expect(member.locator('.block-vars').getByLabel('Name')).toHaveValue('Alex')
    await expect(member.locator('.block-vars').getByLabel('Role')).toHaveValue('Editor')
  })

  test('warns before navigating away while recent edits have not reached storage', async ({ page }) => {
    await page.goto('/admin/pages/create')
    await syncLV(page)
    await page.evaluate(() => window.liveSocket.disconnect())
    await page.getByLabel('Title', { exact: true }).fill('Still on this computer')
    const dialogPromise = page.waitForEvent('dialog')
    const click = page.getByRole('link', { name: 'Pages & Sections' }).click()
    const dialog = await dialogPromise
    expect(dialog.message()).toContain('have not reached recovery storage')
    await dialog.dismiss()
    await click
    await expect(page).toHaveURL(/\/pages\/create$/)
    await expect(page.getByLabel('Title', { exact: true })).toHaveValue('Still on this computer')
    await page.evaluate(() => window.liveSocket.connect())
    await expect(page.getByTestId('draft-status')).toContainText('Recovery copy saved at', { timeout: 25000 })
  })
})
