defmodule Brando.Icons.Legacy do
  @moduledoc """
  Maps Heroicons names to their Lucide replacements.

  Brando used Heroicons until it moved to Lucide. Content saved before the move
  (text block styles, for example) can still carry `hero-*` names, so
  `Brando.Icons.resolve/1` translates them here. New code uses Lucide names.

  The map is keyed by the Heroicons base name. The `hero-` prefix and the
  `-solid`, `-mini` and `-micro` variant suffixes are dropped before lookup,
  since Lucide has a single style. Heroicons whose name is also a Lucide name
  (`sparkles`, `tag`) need no entry.
  """

  @map %{
    "academic-cap" => "graduation-cap",
    "adjustments-horizontal" => "sliders-horizontal",
    "adjustments-vertical" => "sliders-vertical",
    "archive-box" => "archive",
    "archive-box-arrow-down" => "archive-restore",
    "archive-box-x-mark" => "archive-x",
    "arrow-down-on-square" => "square-arrow-down",
    "arrow-down-on-square-stack" => "square-arrow-down",
    "arrow-down-tray" => "download",
    "arrow-left-on-rectangle" => "log-out",
    "arrow-long-down" => "move-down",
    "arrow-long-left" => "move-left",
    "arrow-long-right" => "move-right",
    "arrow-long-up" => "move-up",
    "arrow-path" => "refresh-cw",
    "arrow-path-rounded-square" => "refresh-ccw-dot",
    "arrow-right-on-rectangle" => "log-in",
    "arrow-small-down" => "arrow-down",
    "arrow-small-left" => "arrow-left",
    "arrow-small-right" => "arrow-right",
    "arrow-small-up" => "arrow-up",
    "arrow-top-right-on-square" => "external-link",
    "arrow-trending-down" => "trending-down",
    "arrow-trending-up" => "trending-up",
    "arrow-up-on-square" => "square-arrow-up",
    "arrow-up-on-square-stack" => "square-arrow-up",
    "arrow-up-tray" => "upload",
    "arrow-uturn-down" => "undo-2",
    "arrow-uturn-left" => "undo-2",
    "arrow-uturn-right" => "redo-2",
    "arrow-uturn-up" => "redo-2",
    "arrows-pointing-in" => "minimize-2",
    "arrows-pointing-out" => "maximize-2",
    "arrows-right-left" => "arrow-left-right",
    "arrows-up-down" => "arrow-up-down",
    "at-symbol" => "at-sign",
    "backspace" => "delete",
    "backward" => "rewind",
    "banknotes" => "banknote",
    "bars-2" => "equal",
    "bars-3" => "menu",
    "bars-3-bottom-left" => "text-align-start",
    "bars-3-bottom-right" => "text-align-end",
    "bars-3-center-left" => "text-align-center",
    "bars-4" => "text-align-justify",
    "bars-arrow-down" => "arrow-down-wide-narrow",
    "bars-arrow-up" => "arrow-up-narrow-wide",
    "battery-0" => "battery",
    "battery-100" => "battery-full",
    "battery-50" => "battery-medium",
    "bell-alert" => "bell-ring",
    "bell-slash" => "bell-off",
    "bell-snooze" => "bell-minus",
    "bolt-slash" => "zap-off",
    "bookmark-slash" => "bookmark-x",
    "bookmark-square" => "bookmark",
    "bug-ant" => "bug",
    "building-library" => "landmark",
    "building-office" => "building",
    "building-office-2" => "building-complex",
    "building-storefront" => "store",
    "chart-bar-square" => "chart-column-big",
    "chat-bubble-bottom-center" => "message-square",
    "chat-bubble-bottom-center-text" => "message-square-text",
    "chat-bubble-left" => "message-square",
    "chat-bubble-left-ellipsis" => "message-square-more",
    "chat-bubble-left-right" => "messages-square",
    "chat-bubble-oval-left" => "message-circle",
    "chat-bubble-oval-left-ellipsis" => "message-circle-more",
    "check-badge" => "badge-check",
    "check-circle" => "circle-check",
    "chevron-double-down" => "chevrons-down",
    "chevron-double-left" => "chevrons-left",
    "chevron-double-right" => "chevrons-right",
    "chevron-double-up" => "chevrons-up",
    "chevron-up-down" => "chevrons-up-down",
    "circle-stack" => "database",
    "clipboard-document" => "clipboard",
    "clipboard-document-check" => "clipboard-check",
    "clipboard-document-list" => "clipboard-list",
    "cloud-arrow-down" => "cloud-download",
    "cloud-arrow-up" => "cloud-upload",
    "code-bracket" => "code",
    "code-bracket-square" => "square-code",
    "cog-6-tooth" => "settings",
    "cog-8-tooth" => "cog",
    "command-line" => "square-terminal",
    "computer-desktop" => "monitor",
    "cpu-chip" => "cpu",
    "cube" => "box",
    "cube-transparent" => "box",
    "currency-bangladeshi" => "banknote",
    "currency-dollar" => "dollar-sign",
    "currency-euro" => "euro",
    "currency-pound" => "pound-sterling",
    "currency-rupee" => "indian-rupee",
    "currency-yen" => "japanese-yen",
    "cursor-arrow-rays" => "mouse-pointer-click",
    "cursor-arrow-ripple" => "mouse-pointer-click",
    "device-phone-mobile" => "smartphone",
    "device-tablet" => "tablet",
    "document" => "file",
    "document-arrow-down" => "file-down",
    "document-arrow-up" => "file-up",
    "document-chart-bar" => "file-chart-column",
    "document-check" => "file-check",
    "document-duplicate" => "copy",
    "document-magnifying-glass" => "file-search",
    "document-minus" => "file-minus",
    "document-plus" => "file-plus",
    "document-text" => "file-text",
    "ellipsis-horizontal" => "ellipsis",
    "ellipsis-horizontal-circle" => "circle-ellipsis",
    "ellipsis-vertical" => "ellipsis-vertical",
    "envelope" => "mail",
    "envelope-open" => "mail-open",
    "exclamation-circle" => "circle-alert",
    "exclamation-triangle" => "triangle-alert",
    "eye-dropper" => "pipette",
    "eye-slash" => "eye-off",
    "face-frown" => "face-slightly-frowning",
    "face-smile" => "face-slightly-smiling",
    "finger-print" => "fingerprint-pattern",
    "fire" => "flame",
    "folder-arrow-down" => "folder-down",
    "gif" => "image-play",
    "gift-top" => "gift",
    "globe-alt" => "globe",
    "globe-americas" => "earth",
    "globe-asia-australia" => "earth",
    "globe-europe-africa" => "earth",
    "hand-raised" => "hand",
    "hand-thumb-down" => "thumbs-down",
    "hand-thumb-up" => "thumbs-up",
    "hashtag" => "hash",
    "home" => "house",
    "home-modern" => "house",
    "identification" => "id-card",
    "inbox-arrow-down" => "inbox",
    "inbox-stack" => "inbox",
    "information-circle" => "info",
    "language" => "languages",
    "lifebuoy" => "life-buoy",
    "light-bulb" => "lightbulb",
    "list-bullet" => "list",
    "lock-closed" => "lock",
    "magnifying-glass" => "search",
    "magnifying-glass-circle" => "search",
    "magnifying-glass-minus" => "zoom-out",
    "magnifying-glass-plus" => "zoom-in",
    "microphone" => "mic",
    "minus-small" => "minus",
    "musical-note" => "music",
    "no-symbol" => "ban",
    "paint-brush" => "paintbrush",
    "paper-airplane" => "send",
    "paper-clip" => "paperclip",
    "pencil-square" => "square-pen",
    "phone-arrow-down-left" => "phone-incoming",
    "phone-arrow-up-right" => "phone-outgoing",
    "phone-x-mark" => "phone-off",
    "photo" => "image",
    "play-pause" => "circle-play",
    "plus-small" => "plus",
    "presentation-chart-bar" => "presentation",
    "presentation-chart-line" => "presentation",
    "puzzle-piece" => "puzzle",
    "question-mark-circle" => "circle-question-mark",
    "queue-list" => "list",
    "receipt-percent" => "receipt",
    "receipt-refund" => "receipt",
    "rectangle-group" => "group",
    "rectangle-stack" => "layers",
    "rocket-launch" => "rocket",
    "server-stack" => "server",
    "shield-exclamation" => "shield-alert",
    "signal-slash" => "signal-zero",
    "speaker-wave" => "volume-2",
    "speaker-x-mark" => "volume-x",
    "square-2-stack" => "copy",
    "square-3-stack-3d" => "layers",
    "squares-2x2" => "layout-grid",
    "squares-plus" => "grid-2x2-plus",
    "stop" => "square",
    "swatch" => "swatch-book",
    "table-cells" => "table",
    "trash" => "trash",
    "video-camera" => "video",
    "video-camera-slash" => "video-off",
    "view-columns" => "columns-3",
    "viewfinder-circle" => "scan",
    "window" => "app-window",
    "wrench-screwdriver" => "wrench",
    "x-mark" => "x"
  }

  @variant_suffixes ~w(-solid -mini -micro)

  @doc """
  Returns the Lucide name for a `hero-*` name, or `nil` when there is no
  mapping. The result may itself be a Lucide alias.
  """
  @spec lookup(String.t()) :: String.t() | nil
  def lookup("hero-" <> name) do
    base = strip_variant(name)
    Map.get(@map, base, base)
  end

  def lookup(_name), do: nil

  @doc "The full legacy map, keyed by Heroicons base name."
  @spec map() :: %{String.t() => String.t()}
  def map, do: @map

  defp strip_variant(name) do
    Enum.find_value(@variant_suffixes, name, fn suffix ->
      if String.ends_with?(name, suffix), do: String.replace_suffix(name, suffix, "")
    end)
  end
end
