import { test, expect } from '../test-support/setupAuth'
import { syncLV } from '../utils'

test.beforeEach(async ({ page }) => page.setViewportSize({ width: 1440, height: 1000 }))

async function capture(page, modal, testInfo, name) {
  await expect(modal).toBeVisible()
  await page.evaluate(() => document.fonts.ready)
  await expect(async () => {
    const bounds = await modal.locator(':scope > .modal-dialog').evaluate(el => {
      const r = el.getBoundingClientRect()
      return { left: r.left, right: r.right, bottom: r.bottom, viewport: innerWidth, height: innerHeight }
    })
    expect(bounds.left).toBeGreaterThanOrEqual(0)
    expect(bounds.right).toBeLessThanOrEqual(bounds.viewport)
    expect(bounds.bottom).toBeLessThanOrEqual(bounds.height)
  }).toPass()
  if (await modal.locator('.identifier-picker-nav h3').count()) {
    const leftEdges = await modal.evaluate(el => {
      const icon = el.querySelector('.modal-heading-icon').getBoundingClientRect().left
      const modes = el.querySelector('.link-picker-modes .radios-wrapper, .link-picker-modes .form-tab-customs').getBoundingClientRect().left
      const heading = el.querySelector('.identifier-picker-nav h3')
      const headingText = heading.getBoundingClientRect().left + parseFloat(getComputedStyle(heading).paddingLeft)
      return [icon, modes, headingText]
    })
    expect(Math.max(...leftEdges) - Math.min(...leftEdges)).toBeLessThanOrEqual(0.1)
  }
  await page.screenshot({ path: testInfo.outputPath(`${name}-desktop.png`) })
  await page.setViewportSize({ width: 390, height: 844 })
  const overflow = await modal.evaluate(el => {
    const body = el.querySelector(':scope > .modal-dialog > .modal-content > .modal-body')
    return body.scrollWidth - body.clientWidth
  })
  expect(overflow).toBeLessThanOrEqual(1)
  await expect(modal.locator(':scope > .modal-dialog > .modal-content > .modal-footer')).toBeInViewport()
  await page.screenshot({ path: testInfo.outputPath(`${name}-mobile.png`) })
  if (await modal.locator('.identifier-picker-details').count()) {
    await modal.locator('.identifier-picker-details').scrollIntoViewIfNeeded()
    await page.screenshot({ path: testInfo.outputPath(`${name}-mobile-details.png`) })
    // The content navigation must remain clickable after scrolling the sidebar
    // into view; the search field previously floated over it on mobile.
    await modal.locator('.identifier-picker-nav button.selected').click()
  }
  await page.setViewportSize({ width: 1440, height: 1000 })
}

test('link picker aligns metadata and keeps the selected content through parent updates', async ({ page }, testInfo) => {
  await page.goto('/admin/config/navigation/menus/update/1')
  await syncLV(page)
  await page.locator('#menu_items_0_link_0_identifier_id-field-base .link-preview').click()
  const modal = page.locator('#var-menu_items_0_link_0-link-config')
  await modal.getByLabel('Content', { exact: true }).check()
  await modal.getByRole('button', { name: /All content/ }).click()
  await expect(modal.getByRole('button', { name: /All content/ })).toHaveAttribute('aria-pressed', 'true')
  await modal.locator('.identifier-picker-results input').fill('alpha')
  await expect(modal.locator('.identifier-options .identifier:visible')).toHaveCount(1)
  await expect(modal.locator('[id$="-result-count"]')).toHaveText('1')
  await modal.getByLabel('Link text', { exact: true }).fill('Pending link text')
  await syncLV(page)
  await expect(modal.locator('.identifier-options .identifier:visible')).toHaveCount(1)
  await expect(modal.locator('[id$="-result-count"]')).toHaveText('1')
  await modal.getByRole('button', { name: 'Clear filter', exact: true }).click()
  await modal.locator('.identifier-picker-nav button', { hasText: 'Cases' }).click()
  const selected = modal.locator('.identifier-options .identifier').filter({ hasText: 'Test Project Alpha' })
  await selected.click()
  await syncLV(page)
  await expect(modal.locator('.identifier-picker-details h4')).toHaveText('Test Project Alpha')
  await expect(modal.locator('.modal-person')).toContainText('Creator')
  const alignment = await modal.locator('.modal-metadata').evaluate(el => {
    const values = [el.querySelector('dd > span'), el.querySelector('.modal-status > span')].map(e => e.getBoundingClientRect())
    return Math.abs(values[0].top - values[1].top)
  })
  expect(alignment).toBeLessThanOrEqual(0.1)
  const sidebar = modal.locator('.identifier-picker-details')
  await expect(sidebar.locator('.modal-metadata > div').last().locator('dd > span')).toHaveText(/ · \d{2}:\d{2}$/)
  await expect(sidebar.locator('.identifier-destination-heading')).toHaveCSS('gap', '4px')
  await expect(sidebar.locator('.modal-metadata')).toHaveCSS('margin-top', '16px')
  await expect(sidebar.locator('.person-copy')).toHaveCSS('gap', '8px')
  await modal.getByLabel('Link text', { exact: true }).fill('Featured project')
  await syncLV(page)
  await expect(modal.locator('.identifier-picker-details h4')).toHaveText('Test Project Alpha')
  await capture(page, modal, testInfo, 'link-picker')
  await modal.getByRole('button', { name: 'Done', exact: true }).click()
  await page.getByTestId('submit').click()
  await expect(page).toHaveURL('/admin/config/navigation/menus')
  await page.goto('/admin/config/navigation/menus/update/1')
  await syncLV(page)
  await page.locator('#menu_items_0_link_0_identifier_id-field-base .link-preview').click()
  await expect(modal.getByLabel('Link text', { exact: true })).toHaveValue('Featured project')
  await expect(modal.locator('.identifier-picker-details h4')).toHaveText('Test Project Alpha')
})

test('variable sections retain edits and Escape closes only the nested picker', async ({ page }, testInfo) => {
  await page.goto('/admin/config/content/modules')
  await page.getByRole('button', { name: 'Create new', exact: true }).click()
  await syncLV(page)
  await page.getByRole('tab', { name: /^Variables/ }).click()
  await page.getByRole('button', { name: 'Add variable', exact: true }).click()
  await page.getByRole('button', { name: /^Link / }).click()
  const modal = page.locator('#module-default-var-0')
  await modal.getByLabel('Key', { exact: true }).fill('project_link')
  await modal.getByLabel('Label', { exact: true }).fill('Project link')
  await syncLV(page)
  await capture(page, modal, testInfo, 'variable-editor')
  await modal.getByRole('tab', { name: 'Default value', exact: true }).click()
  const opener = modal.locator('.link-preview').filter({ visible: true })
  await opener.click()
  const nested = modal.locator('.modal--picker')
  await expect(nested).toBeVisible()
  await nested.getByRole('textbox', { name: 'URL', exact: true }).fill('https://example.com/project')
  await syncLV(page)
  await page.keyboard.press('Escape')
  await expect(nested).not.toBeVisible()
  await expect(modal).toBeVisible()
  await expect(opener).toBeFocused()
  await modal.getByRole('tab', { name: 'Definition', exact: true }).click()
  await expect(modal.getByLabel('Label', { exact: true })).toHaveValue('Project link')
  const tab = modal.getByRole('tab', { name: 'Definition', exact: true })
  await tab.focus()
  await tab.press('ArrowDown')
  await expect(modal.getByRole('tab', { name: 'Default value', exact: true })).toBeFocused()
  await expect(modal.getByRole('tab', { name: 'Default value', exact: true })).toHaveAttribute('aria-selected', 'true')
  await opener.click()
  await expect(nested.getByRole('textbox', { name: 'URL', exact: true })).toHaveValue('https://example.com/project')
})

test('block sections preserve config fields and keep advanced actions separate', async ({ page }, testInfo) => {
  await page.goto('/admin/pages/create')
  await syncLV(page)
  await page.getByRole('button', { name: 'Add block', exact: true }).last().click()
  await page.getByRole('button', { name: 'Config Vars', exact: true }).click()
  await syncLV(page)
  const block = page.locator('.entry-block [data-block-uid]').first()
  await block.locator('.block-action-dropdown > .block-action').first().click()
  await block.locator('.block-action-dropdown-content button', { hasText: 'Configure' }).click()
  const modal = page.locator('.modal.visible')
  await modal.getByLabel('Block description', { exact: true }).fill('Project introduction')
  await modal.getByLabel('Config note', { exact: true }).fill('Keep this setting')
  await syncLV(page)
  await capture(page, modal, testInfo, 'block-configuration')
  await modal.getByRole('tab', { name: 'Advanced', exact: true }).click()
  await expect(modal.getByRole('button', { name: 'Fetch missing vars', exact: true })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('block-advanced-desktop.png') })
  await modal.getByRole('tab', { name: 'Settings', exact: true }).click()
  await expect(modal.getByLabel('Config note', { exact: true })).toHaveValue('Keep this setting')
})

test('transfer summary keeps content and recipient visible with the approved tint', async ({ page }, testInfo) => {
  const client = await page.request.post('/__e2e/db/factory', { data: { schema: 'E2eProject.Projects.Client', attributes: { name: 'Transfer client', slug: 'transfer-client', language: 'en', status: 'published' }, creator_id: 2, fields: ['id'] } })
  expect(client.ok(), await client.text()).toBeTruthy()
  const { id: clientId } = await client.json()
  for (const [schema, attributes] of [
    ['Brando.Pages.Page', { title: 'Transfer page', uri: 'transfer-page', language: 'en', status: 'draft' }],
    ['E2eProject.Projects.Project', { title: 'Transfer project', slug: 'transfer-project', client_id: clientId, language: 'en', status: 'draft' }]
  ]) {
    const response = await page.request.post('/__e2e/db/factory', { data: { schema, attributes, creator_id: 2, fields: ['id'] } })
    expect(response.ok(), await response.text()).toBeTruthy()
  }
  await page.goto('/admin/users')
  await syncLV(page)
  const row = page.locator('.list-row').filter({ hasText: 'editor@brandocms.com' })
  await row.getByTestId('circle-dropdown-button').click()
  await row.getByRole('button', { name: 'Delete user', exact: true }).click()
  const modal = page.locator('#transfer-content-modal')
  await modal.getByRole('button', { name: 'Select user...' }).click()
  await modal.locator('.transfer-user-option').filter({ hasText: 'Brando Admin' }).click()
  await expect(modal.locator('.transfer-content-summary tbody tr')).toHaveCount(4)
  await expect(modal.locator('.transfer-content-summary tfoot')).toHaveText('Total5')
  await expect(modal.locator('.transfer-content-summary')).toHaveCSS('background-color', 'rgb(251, 255, 247)')
  await expect(modal.getByRole('button', { name: 'Transfer & Delete', exact: true })).toBeEnabled()
  await capture(page, modal, testInfo, 'transfer-delete')
  await modal.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(row).toBeVisible()
})

test('rich-text link picker applies, cancels and removes links', async ({ page }, testInfo) => {
  async function fixture(schema, attributes) {
    const response = await page.request.post('/__e2e/db/factory', { data: { schema, attributes, creator_id: 1, fields: ['id'] } })
    expect(response.ok(), await response.text()).toBeTruthy()
    return response.json()
  }
  const client = await fixture('E2eProject.Projects.Client', { name: 'Modal client', slug: 'modal-client', status: 'published', language: 'en' })
  const project = await fixture('E2eProject.Projects.Project', { title: 'Link dialog', slug: 'link-dialog', introduction: '<p>View the project</p>', client_id: client.id, status: 'draft', language: 'en' })
  await page.goto(`/admin/projects/projects/update/${project.id}`)
  await syncLV(page)
  const editor = page.locator('[data-footnote-field="introduction"] .tiptap[contenteditable=true]')
  await editor.click()
  await editor.press('ControlOrMeta+a')
  await page.getByRole('button', { name: 'Link', exact: true }).click()
  const modal = page.locator('#tiptap-link-dialog')
  await modal.getByRole('textbox', { name: 'Destination', exact: true }).fill('https://example.com/project')
  await modal.getByRole('button', { name: 'Apply link', exact: true }).click()
  await expect(modal).not.toBeVisible()
  await expect(editor.locator('a')).toHaveAttribute('href', 'https://example.com/project')
  await page.getByRole('button', { name: 'Link', exact: true }).click()
  await modal.getByRole('button', { name: 'Content', exact: true }).click()
  await modal.locator('.identifier-picker-nav button').filter({ hasText: 'Cases' }).click()
  await modal.locator('.identifier-options .identifier').filter({ hasText: 'Test Project Alpha' }).click()
  await expect(modal.locator('.identifier-picker-details h4')).toHaveText('Test Project Alpha')
  await capture(page, modal, testInfo, 'rich-text-link')
  await modal.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(editor.locator('a')).toHaveAttribute('href', 'https://example.com/project')
  await page.getByRole('button', { name: 'Link', exact: true }).click()
  await expect(modal.getByRole('textbox', { name: 'Destination', exact: true })).toHaveValue('https://example.com/project')
  await modal.getByRole('button', { name: 'Remove link', exact: true }).click()
  await expect(editor.locator('a')).toHaveCount(0)
})
