import { test, expect } from '../../test-support/setupAuth'
import { syncLV, confirmUploadFolder } from '../../utils'
import fs from 'node:fs'

async function createPage(page, title, module) {
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/admin/pages/create')
  await syncLV(page)
  await page.getByLabel('Title', { exact: true }).fill(title)
  await page.getByLabel('URI').fill(title.toLowerCase().replaceAll(' ', '-'))
  await page.getByRole('button', { name: 'Add block' }).click()
  await page.getByRole('button', { name: '05 LIVE PREVIEW TEST' }).click()
  await page.getByRole('button', { name: module, exact: true }).click()
  await syncLV(page)
}

async function drop(page, target, files) {
  const payload = files.map(([name, type]) => ({ name, type, bytes: [...fs.readFileSync(`./fixtures/${name}`)] }))
  const transfer = await page.evaluateHandle(files => {
    const transfer = new DataTransfer()
    for (const { name, type, bytes } of files) transfer.items.add(new File([new Uint8Array(bytes)], name, { type }))
    return transfer
  }, payload)
  await target.dispatchEvent('dragenter', { dataTransfer: transfer })
  await target.dispatchEvent('drop', { dataTransfer: transfer })
  await transfer.dispose()
}

const picture = page => page.locator('.picture-block .media-field--block:visible')

test('image drops validate destination, preserve ref settings, and keep the modal usable on mobile', async ({ page }, testInfo) => {
  test.setTimeout(120000)
  const title = 'Media ref settings'
  await createPage(page, title, 'Single Image with Caption')
  await drop(page, picture(page), [['image.jpg', 'image/jpeg'], ['image2.jpg', 'image/jpeg']])
  await expect(picture(page).getByRole('status')).toContainText('Choose one file')
  await expect(picture(page)).not.toHaveAttribute('data-asset-id', /\d+/)
  await drop(page, picture(page), [['image.jpg', 'image/jpeg']])
  const picker = page.locator('#image-picker')
  await expect(picker.getByRole('button', { name: 'Upload here', exact: true })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('upload-folder-desktop.png') })
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(picker.getByRole('button', { name: 'Upload here', exact: true })).toBeInViewport()
  await page.screenshot({ path: testInfo.outputPath('upload-folder-mobile.png') })
  await page.setViewportSize({ width: 1440, height: 1000 })
  await picker.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(picker).not.toBeVisible()
  await expect(picture(page)).not.toHaveAttribute('data-asset-id', /\d+/)
  await drop(page, picture(page), [['image.jpg', 'image/jpeg']])
  await confirmUploadFolder(page)
  await expect(picture(page).locator('img')).toBeVisible({ timeout: 20000 })
  await picture(page).getByRole('button', { name: 'Configure', exact: true }).click()
  const modal = page.getByRole('dialog', { name: 'Configure image', exact: true })
  await modal.getByLabel('Alternative text', { exact: true }).fill('Specific to this reference')
  await modal.getByRole('tab', { name: 'Display', exact: true }).click()
  await modal.getByLabel('Image CSS classes', { exact: true }).fill('hero-image')
  await modal.getByRole('tab', { name: 'Text & link', exact: true }).click()
  await expect(modal.getByLabel('Alternative text', { exact: true })).toHaveValue('Specific to this reference')
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(modal.getByRole('button', { name: 'Done', exact: true })).toBeInViewport()
  const box = await modal.locator('.modal-section-content').boundingBox()
  expect(box.width).toBeGreaterThan(300)
  await modal.getByRole('button', { name: 'Done', exact: true }).click()
  await page.setViewportSize({ width: 1440, height: 1000 })
  await picture(page).getByRole('button', { name: 'Remove', exact: true }).click()
  await drop(page, picture(page), [['image2.jpg', 'image/jpeg']])
  await confirmUploadFolder(page)
  await expect(picture(page).locator('img')).toBeVisible({ timeout: 20000 })
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page).not.toHaveURL(/\/create$/, { timeout: 30000 })
  await page.getByRole('link', { name: title, exact: true }).click()
  await picture(page).getByRole('button', { name: 'Configure', exact: true }).click()
  await expect(modal.getByLabel('Alternative text', { exact: true })).toHaveValue('Specific to this reference')
  await modal.getByRole('tab', { name: 'Display', exact: true }).click()
  await expect(modal.getByLabel('Image CSS classes', { exact: true })).toHaveValue('hero-image')
})

test('a mixed drop on the empty gallery preserves order and survives save', async ({ page }) => {
  test.setTimeout(120000)
  const title = 'Mixed media gallery'
  await createPage(page, title, 'Gallery with Controls')
  const gallery = page.locator('.gallery-block .media-gallery:visible')
  await drop(page, gallery.locator('.media-gallery-empty'), [['image.jpg', 'image/jpeg'], ['video.mp4', 'video/mp4'], ['image2.jpg', 'image/jpeg']])
  await confirmUploadFolder(page)
  await expect(gallery.locator('.gallery-object')).toHaveCount(3, { timeout: 30000 })
  // Both image/video association inputs are carried for every item, preserving typed IDs.
  const mediaIds = () => gallery.locator('.gallery-object').evaluateAll(items => items.map(item => ({
    image: item.querySelector('input[name$="[image_id]"]')?.value,
    video: item.querySelector('input[name$="[video_id]"]')?.value,
  })))
  const before = await mediaIds()
  expect(before[0].image).toMatch(/\d+/)
  expect(before[1].video).toMatch(/\d+/)
  expect(before[2].image).toMatch(/\d+/)
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page).not.toHaveURL(/\/create$/, { timeout: 30000 })
  await page.getByRole('link', { name: title, exact: true }).click()
  await expect(gallery.locator('.gallery-object')).toHaveCount(3, { timeout: 15000 })
  expect(await mediaIds()).toEqual(before)
})

test('the gallery resource editor accepts a mixed drop and saves its collection', async ({ page }) => {
  test.setTimeout(90000)
  const path = '/admin/assets/galleries/update/1'
  await page.goto(path)
  await syncLV(page)
  await page.getByLabel('Configuration target', { exact: true }).fill('default')
  await page.getByLabel('Configuration target', { exact: true }).blur()
  await syncLV(page)
  const gallery = page.locator('[data-kind="resource_gallery"]')
  const initial = await gallery.locator('.gallery-object').count()
  await drop(page, gallery, [['image.jpg', 'image/jpeg'], ['video.mp4', 'video/mp4']])
  await confirmUploadFolder(page)
  await expect(gallery.locator('.gallery-object')).toHaveCount(initial + 2, { timeout: 20000 })
  await expect(gallery.locator('img').last()).toBeVisible({ timeout: 20000 })
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page).not.toHaveURL(path)
  await page.goto(path)
  await syncLV(page)
  await expect(gallery.locator('.gallery-object')).toHaveCount(initial + 2)
})

test('a queued replacement cannot reattach an image after Remove', async ({ page }, testInfo) => {
  await createPage(page, 'Ignore removed upload', 'Single Image with Caption')
  await drop(page, picture(page), [['image.jpg', 'image/jpeg']])
  await confirmUploadFolder(page)
  await expect(picture(page).locator('img')).toBeVisible({ timeout: 20000 })
  // Hold the real manager queue before transfer so the intervening edit is deterministic.
  await page.evaluate(() => { window.BrandoUploads._hook._maxTransfers = 0 })
  await drop(page, picture(page), [['image2.jpg', 'image/jpeg']])
  const queued = page.locator('.upload-item.status-queued').filter({ hasText: 'image2.jpg' })
  await expect(queued).toBeVisible()
  await expect(picture(page).getByRole('status')).toContainText('Waiting to upload')
  await page.screenshot({ path: testInfo.outputPath('field-and-sticky-queue.png') })
  await picture(page).getByRole('button', { name: 'Remove', exact: true }).click()
  await page.evaluate(() => { window.BrandoUploads._hook._maxTransfers = 3; window.BrandoUploads._hook.pumpTransfers() })
  await expect(page.locator('.upload-item.status-done').filter({ hasText: 'image2.jpg' })).toBeVisible({ timeout: 20000 })
  await expect(picture(page).getByRole('button', { name: 'Upload', exact: true })).toBeVisible()
  await expect(picture(page).locator('img')).toHaveCount(0)
})

test('video replacement preserves playback overrides and display settings', async ({ page }, testInfo) => {
  await createPage(page, 'Video ref settings', 'Video Player')
  const field = page.locator('.video-block .media-field--block:visible')
  await drop(page, field, [['video.mp4', 'video/mp4']])
  await expect(field).toHaveAttribute('data-asset-id', /\d+/, { timeout: 20000 })
  const initialId = await field.getAttribute('data-asset-id')
  await field.getByRole('button', { name: 'Configure', exact: true }).click()
  const modal = page.getByRole('dialog', { name: 'Configure video', exact: true })
  await modal.getByRole('tab', { name: 'Playback', exact: true }).click()
  await page.screenshot({ path: testInfo.outputPath('video-playback-desktop.png') })
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(modal.getByRole('button', { name: 'Done', exact: true })).toBeInViewport()
  await page.screenshot({ path: testInfo.outputPath('video-playback-mobile.png') })
  await page.setViewportSize({ width: 1440, height: 1000 })
  const autoplay = modal.getByRole('switch', { name: 'Autoplay', exact: true })
  const expected = (await autoplay.getAttribute('aria-checked')) === 'true' ? 'false' : 'true'
  await autoplay.click()
  await expect(autoplay).toHaveAttribute('aria-checked', expected)
  await modal.getByRole('tab', { name: 'Display', exact: true }).click()
  await modal.getByLabel('Video CSS classes', { exact: true }).fill('feature-video')
  await modal.getByRole('button', { name: 'Done', exact: true }).click()
  await drop(page, field, [['video.mp4', 'video/mp4']])
  await expect(field).not.toHaveAttribute('data-asset-id', initialId)
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page).not.toHaveURL(/\/create$/)
  await page.getByRole('link', { name: 'Video ref settings', exact: true }).click()
  await field.getByRole('button', { name: 'Configure', exact: true }).click()
  await modal.getByRole('tab', { name: 'Playback', exact: true }).click()
  await expect(autoplay).toHaveAttribute('aria-checked', expected)
  await modal.getByRole('tab', { name: 'Display', exact: true }).click()
  await expect(modal.getByLabel('Video CSS classes', { exact: true })).toHaveValue('feature-video')
})

test('file refs keep their settings through replacement and gallery vars accept mixed media', async ({ page }, testInfo) => {
  const response = await page.request.post('/e2e/setup_fixtures/media-upload')
  expect(response.ok()).toBe(true)
  await createPage(page, 'File and gallery settings', 'Media attachment')
  const field = page.locator('.file-block .media-field--block:visible')
  await drop(page, field, [['test.pdf', 'application/pdf']])
  await expect(field).toHaveAttribute('data-asset-id', /\d+/)
  await field.getByRole('button', { name: 'Configure', exact: true }).click()
  const modal = page.getByRole('dialog', { name: 'Configure file', exact: true })
  await modal.getByLabel('Link label', { exact: true }).fill('Download the annual report')
  await modal.getByLabel('CSS class(es)', { exact: true }).fill('report-download')
  await page.screenshot({ path: testInfo.outputPath('file-settings-desktop.png') })
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(modal.getByRole('button', { name: 'Done', exact: true })).toBeInViewport()
  await page.screenshot({ path: testInfo.outputPath('file-settings-mobile.png') })
  await modal.getByRole('button', { name: 'Done', exact: true }).click()
  await page.setViewportSize({ width: 1440, height: 1000 })
  const initial = await field.getAttribute('data-asset-id')
  await drop(page, field, [['test.pdf', 'application/pdf']])
  await expect(field).not.toHaveAttribute('data-asset-id', initial)
  const gallery = page.locator('.media-gallery[data-kind="block_var_gallery"]:visible')
  await gallery.getByRole('button', { name: 'Configure', exact: true }).click()
  const galleryModal = page.getByRole('dialog', { name: 'Gallery', exact: true })
  await expect(galleryModal.getByRole('heading', { name: 'Build your gallery', exact: true })).toBeVisible()
  await page.waitForTimeout(350)
  await page.screenshot({ path: testInfo.outputPath('gallery-editor-empty.png') })
  await drop(page, galleryModal.locator('.media-gallery'), [['image.jpg', 'image/jpeg'], ['video.mp4', 'video/mp4']])
  await expect(page.locator('#image-picker').getByRole('button', { name: 'Upload here', exact: true })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('mixed-destination-desktop.png') })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: testInfo.outputPath('mixed-destination-mobile.png') })
  await page.setViewportSize({ width: 1440, height: 1000 })
  await confirmUploadFolder(page)
  await expect(galleryModal.locator('.gallery-object')).toHaveCount(2, { timeout: 20000 })
  await expect(galleryModal.locator('img')).toBeVisible({ timeout: 20000 })
  await expect(page.locator('#image-picker + .media-drawer-backdrop')).not.toBeVisible()
  await expect(galleryModal.locator('.gallery-item-preview .hero-film')).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('gallery-variable-desktop.png') })
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(galleryModal.getByRole('button', { name: 'Done', exact: true })).toBeInViewport()
  await page.screenshot({ path: testInfo.outputPath('gallery-variable-mobile.png') })
  await page.setViewportSize({ width: 1440, height: 1000 })
  await galleryModal.getByRole('button', { name: 'Done', exact: true }).click()
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page).not.toHaveURL(/\/create$/)
  await page.getByRole('link', { name: 'File and gallery settings', exact: true }).click()
  await expect(gallery).toContainText('2 items')
  await field.getByRole('button', { name: 'Configure', exact: true }).click()
  await expect(modal.getByLabel('Link label', { exact: true })).toHaveValue('Download the annual report')
  await expect(modal.getByLabel('CSS class(es)', { exact: true })).toHaveValue('report-download')
})

test('configured file and video fields browse the current unsaved selection', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/admin/projects/projects/update/3')
  await syncLV(page)
  for (const [kind, name] of [['file', 'test.pdf'], ['video', 'video.mp4']]) {
    const field = page.locator(`#project_cover_${kind}-media`)
    await field.locator('input[type="file"]').setInputFiles(`./fixtures/${name}`)
    await expect(field).toHaveAttribute('data-asset-id', /\d+/, { timeout: 20000 })
    const id = await field.getAttribute('data-asset-id')
    const opener = field.getByRole('button', { name: 'Browse library', exact: true })
    await opener.click()
    const picker = page.locator(`#${kind}-picker`)
    const selected = picker.locator(`.${kind}-picker__${kind}.selected`)
    await expect(selected).toHaveAttribute('phx-value-id', id)
    await expect(page.locator('#brando-nav')).toHaveClass(/phx-connected/)
    await page.screenshot({ path: testInfo.outputPath(`${kind}-browser-desktop.png`) })
    await page.setViewportSize({ width: 390, height: 844 })
    expect(await picker.evaluate(el => el.scrollWidth - el.clientWidth)).toBeLessThanOrEqual(1)
    await page.screenshot({ path: testInfo.outputPath(`${kind}-browser-mobile.png`) })
    await selected.focus()
    await page.keyboard.press('Enter')
    await expect(picker).not.toBeVisible()
    await expect(field).toHaveAttribute('data-asset-id', id)
    await expect(opener).toBeFocused()
    await page.setViewportSize({ width: 1440, height: 1000 })
  }
})
