import { test, expect } from '../../test-support/setupAuth'
import { syncLV } from '../../utils'

async function fixture(page, schema, attributes) {
  const response = await page.request.post('/__e2e/db/factory', { data: { schema, attributes, creator_id: 1, fields: ['id'] } })
  expect(response.ok(), await response.text()).toBeTruthy()
  return response.json()
}

test('rich text links preserve wording through validation, another field change, save and reload', async ({ page }, testInfo) => {
  const client = await fixture(page, 'E2eProject.Projects.Client', { name: 'Editor client', slug: 'editor-client', status: 'published', language: 'en' })
  const project = await fixture(page, 'E2eProject.Projects.Project', { title: 'Editor integration', slug: 'editor-integration', introduction: '<p>Our rooms by the sea.</p>', client_id: client.id, status: 'draft', language: 'en' })
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto(`/admin/projects/projects/update/${project.id}`)
  await syncLV(page)
  // Create after the consumer's route helpers have loaded; old seed URLs may
  // have been generated before the router was loaded by the application.
  await fixture(page, 'E2eProject.Projects.Project', { title: 'Link destination', slug: 'link-destination', introduction: '<p>Our destination.</p>', client_id: client.id, status: 'published', language: 'en' })
  const editor = page.locator('[data-footnote-field="introduction"] .ProseMirror')
  await editor.click()
  await editor.press('ControlOrMeta+a')
  await page.keyboard.type('Havglimt is a small retreat by the sea.')
  await expect(editor).toHaveText('Havglimt is a small retreat by the sea.')
  await editor.press('ControlOrMeta+a')
  await page.getByRole('button', { name: 'Link', exact: true }).click()
  const dialog = page.locator('#tiptap-link-dialog')
  await expect(dialog).toBeVisible()
  await dialog.getByLabel('Destination', { exact: true }).fill('javascript:alert(1)')
  await dialog.getByRole('button', { name: 'Apply link', exact: true }).click()
  await expect(dialog.getByRole('alert')).toContainText('Enter a valid destination')
  await dialog.getByLabel('Destination', { exact: true }).fill('example.com/rooms')
  await page.screenshot({ path: testInfo.outputPath('link-url-desktop.png') })
  await dialog.getByRole('button', { name: 'Apply link', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  await expect(editor.locator('a')).toHaveAttribute('href', 'https://example.com/rooms')
  await expect(editor).toBeFocused()
  await page.getByLabel('Title', { exact: true }).fill('Editor integration updated')
  await syncLV(page)
  await editor.press('ControlOrMeta+z')
  await expect(editor.locator('a')).toHaveCount(0)
  await editor.press('ControlOrMeta+Shift+z')
  await expect(editor.locator('a')).toHaveAttribute('href', 'https://example.com/rooms')
  await page.getByRole('button', { name: 'Save (⌘S)', exact: true }).click()
  await expect(page).toHaveURL(/\/admin\/projects\/projects$/)
  await page.goto(`/admin/projects/projects/update/${project.id}`)
  await syncLV(page)
  await expect(editor).toHaveText('Havglimt is a small retreat by the sea.')
  await expect(editor.locator('a')).toHaveAttribute('href', 'https://example.com/rooms')
  await page.getByRole('button', { name: 'Expand editor', exact: true }).click()
  const expanded = page.getByRole('dialog', { name: 'Introduction', exact: true })
  await expect(expanded.getByRole('heading', { name: 'Introduction', exact: true })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('expanded-editor-desktop.png') })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: testInfo.outputPath('expanded-editor-mobile.png') })
  expect(await expanded.evaluate(el => el.scrollWidth <= el.clientWidth && el.scrollHeight <= el.clientHeight)).toBe(true)
  await expanded.getByRole('button', { name: 'Done', exact: true }).click()
  await expect(editor).toBeFocused()
  await page.setViewportSize({ width: 1440, height: 900 })
  await editor.click()
  await page.getByRole('button', { name: 'Edit link', exact: true }).click()
  await dialog.getByRole('button', { name: 'Content', exact: true }).click()
  await expect(dialog.getByRole('button', { name: /All content/ })).toHaveAttribute('aria-pressed', 'true')
  await dialog.getByRole('textbox', { name: 'Search by title or URL' }).fill('Link destination')
  await expect(dialog.locator('.identifier-options .identifier:visible')).toHaveCount(1)
  await dialog.getByRole('button', { name: /Link destination \/project\/link-destination/ }).click()
  await expect(dialog.getByRole('textbox', { name: 'Search by title or URL' })).toHaveValue('Link destination')
  await expect(dialog.locator('.identifier-options .identifier:visible')).toHaveCount(1)
  await page.screenshot({ path: testInfo.outputPath('link-content-desktop.png') })
  await page.setViewportSize({ width: 390, height: 844 })
  await dialog.getByLabel('Mark as nofollow').scrollIntoViewIfNeeded()
  await page.screenshot({ path: testInfo.outputPath('link-content-mobile.png') })
  expect(await dialog.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
  await dialog.getByRole('button', { name: 'Apply link', exact: true }).click()
  await expect(editor.locator('a')).toHaveAttribute('data-identifier-id', /\d+/)
  await expect(editor.locator('a')).toHaveAttribute('href', '/project/link-destination')
  await expect(editor).toHaveText('Havglimt is a small retreat by the sea.')
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.getByRole('button', { name: 'Save (⌘S)', exact: true }).click()
  await expect(page).toHaveURL(/\/admin\/projects\/projects$/)
  await page.goto(`/admin/projects/projects/update/${project.id}`)
  await expect(editor.locator('a')).toHaveAttribute('href', '/project/link-destination')
  await expect(editor.locator('a')).toHaveAttribute('data-identifier-id', /\d+/)
})
