defmodule BrandoAdmin.Components.Form.Input.RichTextLabels do
  @moduledoc false
  use Gettext, backend: Brando.Gettext

  def labels do
    %{
      toolbar: gettext("Text formatting"),
      paragraph: gettext("Paragraph"),
      heading: gettext("Heading %{level}", level: "%{level}"),
      styles: gettext("Paragraph and style"),
      resetStyle: gettext("Reset paragraph style"),
      bold: gettext("Bold"),
      italic: gettext("Italic"),
      list: gettext("Bulleted list"),
      orderedList: gettext("Numbered list"),
      listTypes: gettext("List types"),
      link: gettext("Link"),
      button: gettext("Button"),
      sub: gettext("Subscript"),
      sup: gettext("Superscript"),
      color: gettext("Text color"),
      resetColor: gettext("Reset color"),
      align: gettext("Alignment"),
      left: gettext("Align left"),
      center: gettext("Align center"),
      right: gettext("Align right"),
      more: gettext("More formatting"),
      blockquote: gettext("Blockquote"),
      underline: gettext("Underline"),
      strike: gettext("Strikethrough"),
      code: gettext("Inline code"),
      codeBlock: gettext("Code block"),
      horizontalRule: gettext("Horizontal rule"),
      clear: gettext("Remove text formatting"),
      undo: gettext("Undo"),
      redo: gettext("Redo"),
      expand: gettext("Expand editor"),
      collapse: gettext("Done"),
      expandedEditing: gettext("Expanded editing"),
      returnToForm: gettext("Return to form"),
      placeholder: gettext("Write something…"),
      anchor: gettext("Page anchor"),
      anchorId: gettext("Anchor name"),
      anchorHelp: gettext("Use a readable name, such as getting-here."),
      anchorInvalid: gettext("Use a name without spaces; it must be unique on this page."),
      apply: gettext("Apply"),
      cancel: gettext("Cancel"),
      remove: gettext("Remove"),
      copyLink: gettext("Copy link"),
      copied: gettext("Link copied"),
      open: gettext("Open link"),
      edit: gettext("Edit link"),
      pasteFallback:
        gettext("Unsupported content was converted to text. Footnotes from another entry need to be added here."),
      changed: gettext("The selected text changed. Try again with the current text."),
      linkFailed: gettext("The link could not be applied. Check the destination and selection."),
      ai: gettext("Write with AI"),
      rewrite: gettext("Rewrite"),
      shorten: gettext("Shorten"),
      continue: gettext("Continue"),
      instruction: gettext("Instructions"),
      generate: gettext("Generate suggestion"),
      aiSuggestion: gettext("AI suggestion"),
      generating: gettext("Writing a suggestion…"),
      accept: gettext("Accept"),
      discard: gettext("Discard"),
      retry: gettext("Try again"),
      aiFailed: gettext("Could not generate a suggestion. Try again."),
      aiAccepted: gettext("Suggestion accepted. Undo is available."),
      words: gettext("%{count} words", count: "%{count}"),
      indent: gettext("Indent list item"),
      outdent: gettext("Outdent list item")
    }
  end
end
