defmodule Brando.Blueprint.ChangesetRunner do
  @moduledoc """
  Executes the runtime changeset pipeline generated by `Brando.Blueprint`.

  Keeping this pipeline outside the compile-time Blueprint facade prevents
  schema recompilation when casting, validation, or trait runtime code changes.
  """

  alias Brando.Blueprint.Assets
  alias Brando.Blueprint.ChangesetParams
  alias Brando.Blueprint.Constraints
  alias Brando.Blueprint.Relations
  alias Brando.Blueprint.Unique
  alias Brando.Blueprint.Villain
  alias Brando.Exception.BlueprintError
  alias Brando.Trait
  alias Ecto.Changeset

  @doc """
  Runs the complete Blueprint changeset pipeline.
  """
  @spec run(ChangesetParams.t()) :: Changeset.t()
  def run(%ChangesetParams{} = changeset_params) do
    start = System.monotonic_time()

    if changeset_params.module != changeset_params.schema.__struct__ do
      raise BlueprintError,
        message:
          "Changeset module/schema mismatch: expected #{inspect(changeset_params.module)}, " <>
            "got #{inspect(changeset_params.schema.__struct__)}"
    end

    changeset =
      changeset_params.schema
      |> Changeset.cast(changeset_params.params, changeset_params.castable_fields)
      |> run_pipeline(changeset_params)

    :telemetry.execute([:brando, :run_changeset], %{duration: System.monotonic_time() - start}, %{
      schema: changeset.data.__struct__
    })

    changeset
  end

  defp run_pipeline(%Changeset{changes: %{marked_as_deleted: true}} = changeset, changeset_params) do
    if changeset_params.module.__allow_mark_as_deleted__() do
      mark_for_deletion(changeset)
    else
      run_validations(changeset, changeset_params)
    end
  end

  defp run_pipeline(changeset, changeset_params), do: run_validations(changeset, changeset_params)

  defp run_validations(changeset, changeset_params) do
    changeset
    |> Relations.run_cast_relations(changeset_params.relations, changeset_params.user)
    |> Assets.run_cast_assets(changeset_params.assets, changeset_params.user)
    |> Villain.maybe_cast_blocks(changeset_params.module, changeset_params.user, changeset_params.opts)
    |> Trait.run_changeset_mutators(
      changeset_params.module,
      changeset_params.traits_before_validate_required,
      changeset_params.user,
      changeset_params.opts
    )
    |> maybe_validate_required(changeset_params.required_castable_fields)
    |> Unique.run_unique_attribute_constraints(changeset_params.module, changeset_params.attributes)
    |> Unique.run_unique_relation_constraints(changeset_params.module, changeset_params.relations)
    |> Constraints.run_validations(changeset_params.module, changeset_params.attributes)
    |> Constraints.run_validations(changeset_params.module, changeset_params.relations)
    |> Constraints.run_fk_constraints(changeset_params.module, changeset_params.relations)
    |> Trait.run_changeset_mutators(
      changeset_params.module,
      changeset_params.traits_after_validate_required,
      changeset_params.user,
      changeset_params.opts
    )
    |> maybe_sequence(changeset_params.module, changeset_params.sequence)
  end

  @doc """
  Applies a sequence when the Blueprint implements the sequenced trait.
  """
  @spec maybe_sequence(Changeset.t(), module(), integer() | nil) :: Changeset.t()
  def maybe_sequence(changeset, _module, nil), do: changeset

  def maybe_sequence(changeset, module, sequence) do
    if module.has_trait(:sequenced) do
      Changeset.change(changeset, sequence: sequence)
    else
      changeset
    end
  end

  @doc """
  Validates required fields unless the changeset is a draft.
  """
  @spec maybe_validate_required(Changeset.t(), [atom()]) :: Changeset.t()
  def maybe_validate_required(changeset, all_required_attrs) do
    case Changeset.get_field(changeset, :status) do
      :draft -> changeset
      _ -> Changeset.validate_required(changeset, all_required_attrs)
    end
  end

  defp mark_for_deletion(changeset) do
    %{
      changeset
      | action: deletion_action(changeset.data),
        changes: %{marked_as_deleted: true},
        errors: [],
        valid?: true
    }
  end

  defp deletion_action(%{__meta__: %{state: :built}} = entry) do
    if primary_key_present?(entry), do: :delete, else: :ignore
  end

  defp deletion_action(%{__meta__: _metadata}), do: :delete

  defp deletion_action(entry) do
    if primary_key_fields(entry) == [] or primary_key_present?(entry), do: :delete, else: :ignore
  end

  defp primary_key_present?(entry) do
    case primary_key_fields(entry) do
      [] -> false
      fields -> Enum.all?(fields, &(not is_nil(Map.get(entry, &1))))
    end
  end

  defp primary_key_fields(entry), do: entry.__struct__.__schema__(:primary_key)
end
