defmodule Brando.Blueprint.URL do
  @moduledoc """
  Resolves URLs through the functions generated by a schema's Blueprint.

  This runtime boundary keeps URL consumers independent of the much larger
  `Brando.HTML` component module.
  """

  alias Brando.RuntimeConfig

  @doc """
  Resolves an entry's Blueprint URL, returning an empty string for values that
  are not Blueprint structs.
  """
  @spec resolve(struct() | term()) :: binary() | nil
  def resolve(%{__struct__: module} = entry), do: module.__absolute_url__(entry)
  def resolve(_entry), do: ""

  @doc """
  Resolves an entry's Blueprint URL and prefixes the configured endpoint host.
  """
  @spec resolve(struct() | term(), :with_host) :: binary()
  def resolve(%{__struct__: module} = entry, :with_host) do
    entry
    |> module.__absolute_url__()
    |> with_hostname()
  end

  def resolve(_entry, :with_host), do: ""

  defp with_hostname(nil), do: hostname()
  defp with_hostname(path), do: Path.join(hostname(), path)

  defp hostname do
    endpoint = RuntimeConfig.web_module(Endpoint)
    "#{endpoint.url()}"
  end
end
