import { test, expect } from '../../test-support/setupAuth'
import { syncLV } from '../../utils'

test('listing summaries preserve edits through collapse, validation and save', async ({ page }, testInfo) => {
  await page.goto('/admin')
  await page.getByRole('link', { name: 'Price categories' }).click()
  await page.getByRole('link', { name: 'Create new' }).click()
  await syncLV(page)
  await page.locator('#price_category_title').fill('Summary prices')
  const row = page.locator('.summary-entry').first()
  await expect(row.getByRole('textbox', { name: 'Title' })).toBeVisible()
  await row.getByRole('textbox', { name: 'Title' }).fill('Consultation')
  await row.getByRole('textbox', { name: 'Price' }).fill('kr 500,-')
  await row.getByRole('button', { name: 'Done', exact: true }).click()
  await expect(row.getByRole('button', { name: 'Edit', exact: true })).toHaveAttribute('aria-expanded', 'false')
  await expect(row.locator('.subform-summary')).toContainText('Consultation')
  await expect(row.locator('.subform-fields')).toBeHidden()
  await page.getByTestId('submit').click()
  await page.getByRole('link', { name: 'Summary prices' }).click()
  await expect(row.locator('.subform-summary')).toContainText('kr 500,-')
  await expect(row.locator('.subform-fields')).toBeHidden()

  await row.getByRole('button', { name: 'Edit', exact: true }).click()
  await row.getByRole('textbox', { name: 'Price' }).fill('kr 750,-')
  await row.getByRole('button', { name: 'Done', exact: true }).click()
  await page.getByRole('button', { name: 'Add entry', exact: true }).click()
  const newRow = page.locator('.summary-entry').last()
  await newRow.getByRole('textbox', { name: 'Title' }).fill('Follow-up')
  await newRow.getByRole('textbox', { name: 'Price' }).fill('kr 250,-')
  await expect(row.locator('.subform-summary')).toContainText('kr 750,-')
  await newRow.getByRole('textbox', { name: 'Price' }).blur()
  await expect(newRow.locator('.subform-summary')).toContainText('kr 250,-')
  await page.locator('.field-wrapper.subform').screenshot({ path: testInfo.outputPath('subform-listing.png') })
  await page.getByTestId('submit').click()
  await page.getByRole('link', { name: 'Summary prices' }).click()
  await expect(page.locator('.summary-entry')).toHaveCount(2)
  await expect(row.locator('.subform-summary')).toContainText('kr 750,-')

  await row.getByRole('button', { name: 'Edit', exact: true }).click()
  await row.getByRole('textbox', { name: 'Title' }).fill('')
  await page.getByTestId('submit').click()
  await page.getByRole('button', { name: 'OK', exact: true }).click()
  await expect(row.getByRole('textbox', { name: 'Title' })).toBeVisible()
  await expect(row.locator('.field-error').first()).toBeVisible()
})
