import { test, expect } from '../../test-support/setupAuth'
import { syncLV, getPreviewFrame, waitForPreviewReady, toggleLivePreview } from '../../utils'

test('switches preview views with unsaved content and restores the selected view', async ({ page }, testInfo) => {
  test.setTimeout(90000)
  await page.setViewportSize({ width: 1680, height: 1050 })
  await page.goto('/admin/pages/create')
  await syncLV(page)
  await page.getByLabel('Title', { exact: true }).fill('A story in progress')
  await page.getByLabel('URI', { exact: true }).fill('a-story-in-progress')
  await page.getByRole('button', { name: 'Add block', exact: true }).click()
  await page.getByRole('button', { name: '05 LIVE PREVIEW TEST' }).click()
  await page.getByRole('button', { name: 'Styled Header', exact: true }).click()
  await syncLV(page)

  const trigger = page.getByRole('button', { name: 'Live preview', exact: true })
  const chooser = page.getByRole('group', { name: 'Preview as' })
  await trigger.click()
  await expect(chooser).toBeVisible()
  await expect(trigger).toHaveAttribute('aria-expanded', 'true')
  await trigger.press('Escape')
  await expect(chooser).toBeHidden()
  await expect(trigger).toBeFocused()

  await trigger.click()
  await chooser.getByRole('button', { name: 'Page Full page with its layout and content', exact: true }).click()
  await waitForPreviewReady(page)
  const frame = getPreviewFrame(page)
  await expect(frame.locator('header[b-tpl="styled-header"] h1')).toContainText('Header Text')
  const key = await page.locator('[name="live_preview[cache_key]"]').inputValue()

  const headerInput = page.locator('.header-block textarea')
  await headerInput.fill('An unsaved block heading')
  await expect(frame.locator('header[b-tpl="styled-header"] h1')).toContainText('An unsaved block heading')

  await trigger.click()
  await chooser.getByRole('button', { name: 'Page listing Your edited page alongside published pages', exact: true }).click()
  await expect(frame.getByRole('heading', { name: 'Pages & stories', exact: true })).toBeVisible()
  await expect(frame.locator('[data-edited="true"] h2')).toHaveText('A story in progress')
  expect(await frame.locator('[data-edited="false"]').count()).toBeGreaterThan(0)
  await expect(page.locator('[name="live_preview[cache_key]"]')).toHaveValue(key)
  await expect(headerInput).toHaveValue('An unsaved block heading')

  await page.getByLabel('Title', { exact: true }).fill('The next chapter')
  await expect(frame.locator('[data-edited="true"] h2')).toHaveText('The next chapter')

  await page.evaluate(() => window.liveSocket.disconnect())
  await page.waitForTimeout(500)
  await page.evaluate(() => window.liveSocket.connect())
  await syncLV(page)
  await waitForPreviewReady(page)
  await expect(frame.locator('[data-edited="true"] h2')).toHaveText('The next chapter')
  await expect(page.locator('[name="live_preview[cache_key]"]')).toHaveValue(key)

  await expect(page.locator('.live-preview')).toHaveCSS('opacity', '1')
  await page.getByRole('heading', { name: 'Create page', exact: true }).scrollIntoViewIfNeeded()
  await trigger.click()
  await expect(chooser.locator('[aria-pressed="true"]')).toContainText('Page listing')
  await page.screenshot({ path: testInfo.outputPath('preview-target-chooser.png'), fullPage: false })
  await page.locator('.form-content > .form-tabs').screenshot({ path: testInfo.outputPath('preview-toolbar.png') })
  // Click-away dismisses without disturbing the active preview.
  await page.getByLabel('Title', { exact: true }).click()
  await expect(chooser).toBeHidden()
  await expect(frame.locator('[data-edited="true"]')).toBeVisible()

  await page.setViewportSize({ width: 1280, height: 900 })
  await expect(page.locator('.form-content > .form-tabs')).toBeInViewport({ ratio: 1 })
  await expect(page.locator('.live-preview-targets')).toBeInViewport({ ratio: 1 })
  await page.locator('.form-content > .form-tabs').screenshot({ path: testInfo.outputPath('preview-toolbar-compact.png') })

  await trigger.click()
  await chooser.getByRole('button', { name: 'Page Full page with its layout and content', exact: true }).click()
  await expect(frame.locator('header[b-tpl="styled-header"] h1')).toHaveText('An unsaved block heading')
  await page.locator('.live-preview-refresh').click()
  await expect(page.locator('.live-preview iframe')).toHaveAttribute('data-live-preview-device', 'desktop')
  await expect(frame.locator('header[b-tpl="styled-header"] h1')).toHaveText('An unsaved block heading')
  await toggleLivePreview(page)
  await expect(page.locator('.live-preview-wrapper')).toBeHidden()
})
