import { createHmac } from 'node:crypto'
import { test, expect } from '../../test-support/setupAuth'
import { syncLV } from '../../utils'

test.describe('Markdown source placements', () => {
  test.setTimeout(90000)
  test.beforeEach(async ({ page }) => page.setDefaultTimeout(15000))

  test('connect, approve an exact version, save and reload, then follow a signed push', async ({ page }, testInfo) => {
    expect((await page.request.post('/e2e/setup_fixtures/markdown-source')).ok()).toBeTruthy()
    await page.setViewportSize({ width: 1440, height: 1100 })
    await page.goto('/admin/config/markdown-sources')
    await expect(page.getByRole('heading', { name: 'Installation guide' })).toBeVisible()
    await page.screenshot({ path: testInfo.outputPath('sources-desktop.png'), fullPage: true })
    await page.setViewportSize({ width: 390, height: 844 })
    await page.screenshot({ path: testInfo.outputPath('sources-mobile.png'), fullPage: true })
    await page.setViewportSize({ width: 1440, height: 1100 })

    await page.goto('/admin/pages/create')
    await page.getByRole('radio', { name: 'Published', exact: true }).check()
    await page.getByLabel('Title', { exact: true }).fill('Connected documentation')
    await page.getByLabel('URI', { exact: true }).fill('connected-documentation')
    await page.getByRole('button', { name: 'Add block', exact: true }).last().click()
    await page.getByRole('button', { name: '05 LIVE PREVIEW TEST' }).click()
    await page.getByRole('button', { name: 'Repository document', exact: true }).click()
    await syncLV(page)

    const editor = page.locator('.markdown-source-editor')
    await editor.getByLabel('Source', { exact: true }).selectOption({ label: 'Installation guide' })
    await syncLV(page)
    await expect(editor.getByLabel('Update policy')).toHaveValue('review')
    await editor.getByLabel('Preview a version').selectOption(await editor.getByLabel('Preview a version').locator('option').filter({ hasText: 'aaaaaaaaaaaa' }).getAttribute('value'))
    await expect(editor.getByRole('region', { name: 'Markdown preview' })).toContainText('First guide')
    await editor.getByRole('button', { name: 'Use displayed version' }).click()
    await syncLV(page)
    await expect(editor.locator('input[type=hidden][name$="[version_id]"]')).not.toHaveValue('')
    await editor.screenshot({ path: testInfo.outputPath('placement-desktop.png') })
    await page.getByRole('button', { name: 'Save', exact: true }).click()
    await expect(page).toHaveURL(/\/admin\/pages$/)
    await page.getByRole('link', { name: 'Connected documentation', exact: true }).click()
    await expect(editor.getByLabel('Update policy')).toHaveValue('review')
    await expect(editor).toContainText('aaaaaaaaaaaa')
    const editURL = page.url()
    expect(await (await page.request.get('/connected-documentation')).text()).toContain('First guide')

    // Source import doesn't save an open form or advance the accepted version.
    await page.getByLabel('Title', { exact: true }).fill('Unsaved local title')
    const push = async (commit = 'b') => {
      const body = JSON.stringify({ repository: { id: 2582 }, ref: 'refs/heads/main', after: commit.repeat(40), deleted: false })
      const signature = createHmac('sha256', 'e2e-markdown-webhook-secret-do-not-use-in-production').update(body).digest('hex')
      return page.request.post('/api/markdown-sources/webhooks/e2e-docs', { data: body, headers: { 'content-type': 'application/json', 'x-hub-signature-256': `sha256=${signature}`, 'x-github-event': 'push', 'x-github-delivery': `markdown-e2e-delivery-2582-${commit}` } })
    }
    expect((await push()).status()).toBe(202)
    await editor.getByRole('button', { name: 'Check available versions' }).click()
    await expect(editor).toContainText('aaaaaaaaaaaa')
    await expect(page.getByLabel('Title', { exact: true })).toHaveValue('Unsaved local title')
    expect(await (await page.request.get('/connected-documentation')).text()).toContain('First guide')

    // A newer import cannot broaden approval of an already displayed version.
    const second = await editor.getByLabel('Preview a version').locator('option').filter({ hasText: 'bbbbbbbbbbbb' }).getAttribute('value')
    await editor.getByLabel('Preview a version').selectOption(second)
    await expect(editor.getByRole('region', { name: 'Markdown preview' })).toContainText('Second guide')
    expect((await page.request.post('/e2e/setup_fixtures/markdown-source-third')).ok()).toBeTruthy()
    expect((await push('c')).status()).toBe(202)
    await editor.getByRole('button', { name: 'Check available versions' }).click()
    await expect(editor.getByRole('region', { name: 'Markdown preview' })).toContainText('Second guide')
    await editor.getByRole('button', { name: 'Use displayed version' }).click()
    await syncLV(page)
    await expect(editor.locator('input[type=hidden][name$="[version_id]"]')).toHaveValue(second)
    await page.evaluate(() => window.liveSocket.disconnect())
    await expect(page.locator('.phx-connected').first()).toBeHidden()
    await page.evaluate(() => window.liveSocket.connect())
    await syncLV(page)
    await expect(editor.locator('input[type=hidden][name$="[version_id]"]')).toHaveValue(second)
    await expect(page.getByLabel('Title', { exact: true })).toHaveValue('Unsaved local title')
    await page.getByRole('button', { name: 'Save', exact: true }).click()
    await expect(page).toHaveURL(/\/admin\/pages$/)
    expect(await (await page.request.get('/connected-documentation')).text()).toContain('Second guide')
    await page.goto(editURL)

    await editor.getByLabel('Update policy').selectOption('follow')
    await syncLV(page)
    await expect(editor).toContainText('cccccccccccc')
    await page.getByRole('button', { name: 'Save', exact: true }).click()
    await expect(page).toHaveURL(/\/admin\/pages$/)
    await page.goto(editURL)
    await expect(editor.getByLabel('Update policy')).toHaveValue('follow')
    expect((await page.request.post('/e2e/setup_fixtures/markdown-source-fourth')).ok()).toBeTruthy()
    expect((await push('d')).status()).toBe(202)
    expect(await (await page.request.get('/connected-documentation')).text()).toContain('Fourth guide')
    expect((await push('d')).status()).toBe(202)
    await editor.getByRole('button', { name: 'Check available versions' }).click()
    await expect(editor).toContainText('dddddddddddd')
    await page.setViewportSize({ width: 390, height: 844 })
    await page.screenshot({ path: testInfo.outputPath('placement-mobile.png'), fullPage: true })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  })
})
