#! /bin/sh

# Pull latest source code from git master.
# Get dependencies, and update Brando
# Build production assets
# Compile project

git pull
MIX_ENV=prod mix deps.get
MIX_ENV=prod mix deps.update brando
node_modules/brunch/bin/brunch build --production
MIX_ENV=prod mix compile
