name: CI

on: [push, pull_request]

jobs:
  format:
    name: format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install OTP and Elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: 22.2
          elixir-version: 1.10.2

      - name: Install dependencies
        run: mix deps.get

      - name: Run "mix format"
        run: mix format --check-formatted

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pair:
          - erlang: 22.2
            elixir: 1.10.2
          - erlang: 22.1
            elixir: 1.9.4
          - erlang: 21.3
            elixir: 1.8.2

    steps:
      - uses: actions/checkout@v1

      - name: Install OTP and Elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: ${{matrix.pair.erlang}}
          elixir-version: ${{matrix.pair.elixir}}

      - name: Install dependencies
        run: mix deps.get

      - name: Run tests
        run: mix test --trace